<?php

use App\Models\Enums\AdoptStat;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AdoptTable extends Migration
{
    public function up()
    {
      Schema::create('adopt', function (Blueprint $table) {
        $table->increments('adopt_id');
        $table->char('stat', 1);
        $table->string('name', 50);
        $table->string('slug', 50);
        $table->char('gender', 1);
        $table->date('birthday');
        $table->string('breed', 50);
        $table->string('colour', 20)->nullable();
        $table->boolean('microchip')->nullable();
        $table->boolean('vaccinate')->nullable();
        $table->boolean('sterilise')->nullable();
        $table->boolean('hdb');
        $table->string('image', 100);
        $table->string('microchip_no', 40)->nullable();
        $table->date('microchip_date')->nullable();
        $table->date('vaccinate_date1')->nullable();
        $table->date('vaccinate_date2')->nullable();
        $table->date('vaccinate_date3')->nullable();
        $table->date('sterilise_date')->nullable();
        $table->string('vet', 40)->nullable();
        $table->string('location', 30)->nullable();
        $table->string('location_other', 30)->nullable();
        $table->string('health', 500)->nullable();
        $table->string('behaviour', 500)->nullable();
        $table->string('history', 2000)->nullable();
        $table->dateTime('rescued_on')->nullable();
        $table->string('posted_by', 30);
        $table->dateTime('posted_on');
        //$table->boolean('has_foster');
        //$table->boolean('can_sponsor');
        $table->string('desc', 2000)->nullable();
        $table->softDeletes();
      });
  
      //export from adoptadog
      //SELECT `name`, 'A' as `stat`, '''''' as `slug`, `gender`, `birthday`, `breed`, '''''' as `colour`, 1 as `microchip`, 1 as `vaccinate`, 1 as `sterilise`, if(hdb = 'Y', 1, 0) as `hdb`, `image`, replace(replace(adopt_desc, '"', '\"'), "'", "\'") as `desc`, 'admin' as `posted_by`, '2018-07-15' as `posted_on` FROM `adopt` WHERE post_user = 'asd' and adopt_stat = 'a'
      
      DB::statement('
INSERT INTO `adopt` (`name`, `stat`, `slug`, `gender`, `birthday`, `breed`, `colour`, `microchip`, `vaccinate`, `sterilise`, `hdb`, `image`, `desc`, `posted_by`, `posted_on`) VALUES
("Natasha","A","","F","2013-03-01","Cross Breed","","1","1","1","0","natasha.jpg","<p>A bright and curious girl, Natasha is loving yet independent. Loves to hop onto your lap for kisses. Natasha and her sisters, Nathalie and Nadia, were rescued from a farm in Neo Tiew.</p>","admin","2018-07-15"),
("Lucas","A","","M","2012-01-01","Cross Breed","","1","1","1","0","lucas.jpg","Lucas is a local cross breed who is great with people. He is playful and affectionate. Lucas was one of the many starving strays who used to scrounge for food in the wilds of Lim Chu Kang.","admin","2018-07-15"),
("Trudy","A","","F","2012-07-01","Cross Breed","","1","1","1","0","trudy_65.jpg","<p>Trudy is playful and friendly. Trudy is one of a litter of 5 puppies found in the Tuas area which were surrendered to the AVA.</p>","admin","2018-07-15"),
("Spotty","A","","M","2011-09-01","Cross Breed","","1","1","1","0","spotty.jpg","Spotty is active, affectionate, human-friendly, good with children and selective with dogs, although he does get along pretty well with most dogs. He is also very food/treats motivated, that makes him very trainable and he learns fast. For more info on him: http://www.sportyspotty.com. Spotty was found wandering at a market in Ang Mo Kio looking lost, tired and hungry. We suspected that he had been abandoned ","admin","2018-07-15"),
("Yasmin","A","","F","2012-06-01","Cross Breed","","1","1","1","0","yasmin.jpg","Yasmin is a very sweet puppy and is very affectionate towards her caregivers. She is attentive and loves to play with other dogs. She has a wonderful temperament and is well behaved all the time. Yasmin is a very smart puppy and will make a great companion for anyone. Yasmin was rounded up together with a few other dogs and puppies at Yishun Park and sent to the AVA .","admin","2018-07-15"),
("Jacob","A","","M","2010-01-01","Cross Breed","","1","1","1","1","jacob.jpg","Headstrong and dominant, rescued from Jurong Island","admin","2018-07-15"),
("Fannie","A","","F","2010-02-01","Cross Breed","","1","1","1","1","fannie.jpg","Friendly. The smallest of her litter.  Rescued from a carpark opposite the Tampines fire station with her 4 siblings.","admin","2018-07-15"),
("Fido","A","","M","2010-02-01","Cross Breed","","1","1","1","0","fido.jpg","Friendly. Rescued from a carpark opposite the Tampines fire station with his 4 siblings ","admin","2018-07-15"),
("Avery","A","","F","2008-01-01","Cross Breed","","1","1","1","0","avery.jpg","A little wary of strangers but warms up quite fast. Calm, quiet and easy to manage.  ASD was alerted to Avery\'s plight towards the end of 2009. She was a young female who had been impregnated by a member of a pack of stray dogs roaming the MacRitchie Reservoir area. Avery was living in the jungle in Adam Drive with her 2 puppies and barely had enough food to survive, let alone feed her pups. The 2 puppies were caught by a man driving a van one day and as Avery was his next target, she was quickly rescued.","admin","2018-07-15"),
("Mommy Girl","A","","F","2006-01-01","Cross Breed","","1","1","1","1","mommygirl.jpg","Quiet and friendly. Mommy Girl was a stray in the Ubi area and gave birth to 8 puppies in an open carpark. All her puppies have already found forever homes except for Zeus who shares the same kennel as her at the ARC. Mother and son are very close.","admin","2018-07-15"),
("Zeus","A","","M","2007-07-01","Cross Breed","","1","1","1","0","zeus.jpg","Active and playful. Rescued from Ubi with his 7 siblings and mother ","admin","2018-07-15"),
("Biscuit","A","","M","2007-10-01","Cross Breed","","1","1","1","0","biscuit.jpg","Active and playful. She was rescued by a vet.","admin","2018-07-15"),
("Moon","A","","F","2008-01-01","Cross Breed","","1","1","1","0","moon.jpg","A very sweet girl who is gentle and quiet and good with humans.  Rescued from a flooded drain in the Lim Chu Kang area together with her 3 puppies, all of whom have since been adopted.","admin","2018-07-15"),
("Yummie","A","","M","2008-02-01","Cross Breed","","1","1","1","0","yummie.jpg"," Friendly and playful as a puppy but has grown shy and timid due to lack of socialisation with humans. Rescued from Yishun.","admin","2018-07-15"),
("Kranji Girl","A","","F","2007-01-01","Cross Breed","","1","1","1","0","kranjigirl.jpg","Needs time to warm up to people. ASD took her in as a stray to be sterilised and then released (TNR) but later decided to keep her and find her a home.","admin","2018-07-15"),
("Noisy","A","","M","2007-01-01","Cross Breed","","1","1","1","0","noisy.jpg","Noisy is a big baby who likes to play rough and jump on people. He is very good with humans and will welcome people he recognises with loud and happy barks. He was a stray at Kranji coffee shop who was rescued as pest control was trying to catch him.","admin","2018-07-15"),
("Winner","A","","M","2009-03-01","Cross Breed","","1","1","1","0","winner.jpg","So far he has not tried to attack any humans but he can be quite rough and boisterous, jumping on people and biting objects. However with treats, he can do a sit and wait and also walks well on leash.  Winner was found in Woodlands when he was a month old and was adopted one month later. However he was returned to ASD as the adoptive family complained about him biting the domestic help. This could be due to the fact that the family did not give Winner much attention or training. ","admin","2018-07-15"),
("Polly","A","","F","2008-06-01","Cross Breed","","1","1","1","0","polly.jpg"," Takes time to warm up to people. She was found all alone in Pasir Panjang at one month of age, crying with hunger.","admin","2018-07-15"),
("Nature","A","","F","2016-05-01","Cross Breed","","1","1","1","0","nature.jpg","<p>Was very playful and affectionate as a puppy but has grown quite timid and shy due to lack of interaction with people. Found at Macritchie Reservior.</p>","admin","2018-07-15"),
("Leo","A","","M","2009-01-01","Cross Breed","","1","1","1","0","leo-122.jpg","<p>Friendly and happy to see people. A hit and run victim found in a drain in the Lim Chu Kang area. Suffered two broken legs but has since recovered.</p>","admin","2018-07-15"),
("Lucky Strike","A","","M","2008-06-01","Cross Breed","","1","1","1","0","luckystrike.jpg","<p>A little timid. Afraid of heavy vehicles and loud noises. Offspring of Tiger Stripe.</p>","admin","2018-07-15"),
("Black Bingo","A","","M","2007-06-01","Cross Breed","","1","1","1","0","blackbingo.jpg","<p>""Selective with people. Would make a good guard dog as he is alert at all times and barks at strangers"" Found in Ang Mo Kio. Was run over by a lorry and had to undergo surgery on his hind leg</p>","admin","2018-07-15"),
("Lava","A","","F","2009-05-01","Cross Breed","","1","1","1","0","lava.jpg","A shy puppy, happy to lick and enjoy a pat once she gets to know you, but slow to warm up. Lacks confidence in new environments; will need time to adjust and slow introductions to new people and environments. Easy to handle, non-aggressive, enjoys company of other dogs. Lava\'s personality will emerge once she\'s in a safe and loving home. A delightful pup, great pet in the right home. Part of a pack of strays in one of our feeding programmes in Kranji this little sweetheart was targeted for neuter & release in Sept 2009 but she so endeared herself to the kennel staff with her friendly personality and waggy tail that after spaying we decided to place her in our rehoming programme. Her mother is a medium sized brown/white local cross.","admin","2018-07-15"),
("Elf","A","","F","2008-02-01","Cross Breed","","1","1","1","0","elf.jpg","Intelligent and alert but needs time to warm up to people.  Elf was found by the side of the road in the Lim Chu Kang area. She was 6 - 7 months old then but her rescuers initially thought that she was only 4 months old as she was tiny due to malnutrition. Her sister had died of starvation and Elf just stayed close to her body as there was nowhere else for her to go. When the vet checked her teeth for her age, it was found that Elf had been chewing on stones and dried leaves to survive. ","admin","2018-07-15"),
("Kodomo","A","","F","2006-05-01","Cross Breed","","1","1","1","0","kodomo.jpg","<p>Very jumpy and active. Barkish if confined.</p>","admin","2018-07-15"),
("Lucky Hawkins","A","","M","2012-06-01","Cross breed","","1","1","1","1","luckyhawkins.jpg","<div>Description: Lucky Hawkins is a happy, confident, trusting and manja boy. His right hind leg is slightly weak because of his dislocated hip but he walks (and even trots) fine and is very relaxed and comfortable on leash. He can be a bit rough when playing so he would need a good pack leader who can discourage such bad habits.</div>
<div>&nbsp;</div>
<div>History: Lucky Hawkins was a stray who was cared for by the smallholders at a hawker centre in Tuas. He was hit by a motorcycle one day and suffered a dislocated hip.</div>","admin","2018-07-15"),
("Siew Mai","A","","M","2008-07-01","Cross Breed","","1","1","1","0","siewmai.jpg","<div>Siew Mai is friendly, laid back and calm and easy to walk on leash.</div>
<div><br /></div>
<div>History: Siew Mai was a factory dog who was abandoned because the management moved out.</div>","admin","2018-07-15"),
("Lucky Boy","A","","M","2008-07-01","Cross Breed","","1","1","1","0","lucky boy_320.jpg","<p>Description: Lucky Boy was rescued as he needed to be treated for cancer at the vet but after he was cured, his rescuer decided to rehome him instead of releasing him back as he has a good temperament and is friendly towards people. He has learnt to walk comfortably on leash.</p>
<p>History: Lucky Boy was a stray from Woodlands who contracted a transmissible tumor. However after a course of chemotherapy, he is completely cured.&nbsp;</p>","admin","2018-07-15"),
("Louie","A","","M","2013-11-01","Cross Breed","","1","1","1","0","louie_332.jpg","<p>Description: Louie is the only one in his pack with big, round, floppy ears which makes him look like a labrador puppy. He is a happy boy who loves his toys and being hugged.</p>
<p>History: Louie is one out of a litter of ten puppies from a stray female in the Pandan Loop area.</p>","admin","2018-07-15"),
("Ke Ke","A","","M","2013-09-01","Cross Breed","","1","1","1","1","ke ke_335.jpg","<p>Description: Ke Ke may be shy initially but he is very affectionate once he warms up. He is an intelligent boy who will benefit from training.</p>
<p>&nbsp;</p>
<p>History: Ke Ke was rescued from Tuas with his brother, Ai Ai.</p>","admin","2018-07-15"),
("Ai Ai","A","","M","2013-09-01","Cross Breed","","1","1","1","0","ai ai_336.jpg","<p>Description: Ai Ai is shy but warms up after he gets acquainted. He is intelligent, playful and good natured.</p>
<p>History: Ai Ai was rescued from Tuas with his brother, Ke Ke.&nbsp;</p>","admin","2018-07-15"),
("Kirstie","A","","F","2014-01-01","Cross Breed","","1","1","1","0","kirstie_360.JPG","<p>Description: Kirstie is an adorable girl who is confident and quick to learn.</p>
<p>&nbsp;</p>
<p>History: Kirstie was rescued from a canal by the Kranji Expressway (KJE) with her 3 siblings after 2 other siblings were caught by the authorities.</p>","admin","2018-07-15"),
("Bruno","A","","M","2010-01-01","Cross Breed","","1","1","1","0","bruno_363.jpg","<p>Description: Bruno is a very handsome boy and looks like he could be a rottweiler cross. He possesses a happy and friendly nature and an extremely waggy tail! He is excellent indoors and is careful around furniture (no shredding or clawing at furniture) but he needs to know what is considered a toy and what is not. He is eager to be trained, but not overly excitable. Bruno is extremely perceptive and knows how to read your mood. He will only seek attention from you when he knows you are free. Otherwise he will keep his distance and is content to just watch you and wait for you to pay attention to him.</p>
<p>&nbsp;</p>
<p>History: Bruno was found abandoned in Ponggol with heart worm and tick fever. He has already been treated for these conditions and is in the pink of health now.</p>","admin","2018-07-15"),
("Tiffany","A","","F","2013-09-01","Cross Breed","","1","1","1","0","tiffany_365.jpg","<p>Description: Tiffany has a sweet and gentle disposition. She is a little shy but warms up fairly quickly and once she does, she is very friendly and affectionate. Tiffany enjoys walks and is good on the leash. She is a little clumsy at times and we suspect that the sight in her right eye must have been affected when she suffered a head trauma when she was younger.</p>
<p>History: Tiffany was found lying motionless by a worker in Tuas when she was only 3 months old. She remained listless for about a week and slept most of the time. She perked up eventually and before long, she was standing, then walking then running. We concluded that she had suffered a head trauma which rendered her immobile temporarily. However, we suspect that the trauma might have caused her to lose sight in the right eye.</p>","admin","2018-07-15"),
("Elly","A","","F","2014-02-01","Cross Breed","","1","1","1","0","elly_416.jpg","<p>Description: Elly has a sweet disposition but takes a while to warm up to people and other dogs. She\'s paper trained, understands basic commands and loves walks.</p>
<p>History: Elly was a stray puppy living with her 2 siblings at a workers\' dormitory in Tuas when she was caught and impounded by the authorities.</p>","admin","2018-07-15"),
("Lucy","A","","F","2014-03-01","Cross Breed","","1","1","1","0","lucy_519.jpg","<p>Description: Looking at Lucy, you will never guess that she came so close to death. She is a playful and active little sweetheart but also very strong willed and bold - a true mark of a survivor. She shows affection by playfully nipping your fingers and whimpers softly when she cannot see anyone but is quiet when she is around you.</p>
<p>History: Lucy was found in a very deep drain in Lim Chu Kang and was in danger of being swept away before she was rescued.</p>","admin","2018-07-15"),
("Lottie","A","","F","2012-01-01","Cross Breed","","1","1","1","0","lottie_535.jpg","<p>Description: Lottie is a charmer and wags her tail constantly. She smiles at you and gently takes treats from your hands. She loves to be patted and having her ears ruffled.</p>
<p>History: Lottie suddenly appeared in the Lim Chu Kang area and was rescued as she could not fend for herself. When she was brought to the vet to be checked up, she was found to be sterilised so she was obviously abandoned.</p>","admin","2018-07-15"),
("Phelix","A","","M","2014-03-01","Cross Breed","","1","1","1","0","phelix_544.jpg","<p>Description: Very loving once warmed up, playful.</p>
<p>History: Pete was saved from a factory which was closing down just in the nick of time as he tested positive for canine parvovirus which can be fatal. Fortunately he received the necessary treatment and has now fully recovered.</p>","admin","2018-07-15"),
("Ding Ding","A","","M","2014-01-01","Cross Breed","","1","1","1","0","ding ding_548.jpg","<p>Description: Ding Ding is an excellent and obedient companion. He enjoys playing with his family members. Although timid at first, Ding Ding slowly but surely gets accustomed to new environments quickly. He is intelligent and sweetly vocalises his needs such as when he is hungry or needs to use the bathroom. Ding Ding is a curious, friendly, brave and handsome little boy who doesn\'t ask for much.</p>
<p>History: Ding Ding was a stray puppy living with his 2 siblings at a workers\' dormitory in Tuas when he was caught and impounded by the authorities.</p>","admin","2018-07-15"),
("Bobbi","A","","F","2012-01-01","Cross Breed","","1","1","1","1","bobbi_549.jpg","<p>Description: Bobbi is a very friendly and affectionate dog who likes being in the company of people.</p>
<p>History: Bobbi was a stray living an idyllic life in the Brickland Road area together with a few other dogs. When one of the pack members got caught by the authorities, we decided to whisk Bobbi and her friends to safety.</p>","admin","2018-07-15"),
("Hercules","A","","M","2009-01-01","Cross Breed","","1","1","1","0","hercules_550.jpg","<p>natured dog. He is always happy to meet people and make new friends.</p>
<p>History: Hercules was kept in a small cage when he was a young puppy resulting in him being bow legged. Fortunately, he was adopted by an expatriate family who lived in a big house with a garden but when the family relocated back to Australia, they left Hercules and another dog, Yvette, behind.</p>","admin","2018-07-15"),
("Jolene","A","","F","2014-10-01","Cross Breed","","1","1","1","1","jolene_551.jpg","<p>Description: Jolene is a happy go lucky girl who makes friends instantly with everyone she meets and loves company. She is playful, intelligent and curious.</p>
<p>History: Jolene was stray living at a factory in the Lok Yang industrial area.</p>
<p>&nbsp;</p>","admin","2018-07-15"),
("Bheen","A","","M","2012-01-01","Local Cross","","1","1","1","0","bheen.jpg","Description: Bheen is friendly and confident dog who will make a good guard dog for a loving family.<br><br>History: Bheen was found wandering around a block of HDB flats in the West Coast area. He had a microchip but when the owner was found, he did not want Bheen anymore.","admin","2018-07-15"),
("Polo","A","","M","2011-01-01","Local Cross","","1","1","1","0","polo.jpg","Description: Polo is a loveable and goofy boy who loves meeting people and making new friends. He loves his food and walks great on leash. <br><br>History: Polo was living at a factory in Pioneer Road with another dog when the management surrendered them both to the authorities. After we claimed the two dogs from the pound, we sent them to the vet for a health check out and discovered that both had contracted distemper, a deadly and contagious disease. They were warded immediately and spent one month in an isolation ward. Polo managed to pull through but unfortunately the other dog did not make it. Today, Polo is free from distemper and in the pink of health though he still has a slight twitch, a lingering symptom of the disease. ","admin","2018-07-15"),
("Lilibet","A","","F","2010-01-01","Local Cross","","1","1","1","1","lilibet.jpg","Description: Lilibet is shy and hesitant on first meeting but once she trusts you, she will come to you for affection.<br><br>History: Lilibet was a stray from the Brickland Road area who was caught by the authorities and bailed out.","admin","2018-07-15"),
("Tam","A","","M","2013-02-01","Cross Breed","","1","1","1","0","tam_735.jpg","<p>Description: Tam is a handsome and loving boy who takes a short time to warm up to people. He is great with other dogs (a follower) and good with people who are firm with him. He is not high energy and is food motivated. He loves going to the dog run but is not keen on long walks. Tam is trained to do his business outside the house.</p>","admin","2018-07-15"),
("Kadek","A","","M","2011-01-01","Cross Breed","","1","1","1","1","kadek.jpg","<p>Description: Kadek is independent with a placid temperament and is good with people and other dogs. He was named ""Kadek"" because of his short legs!</p>
<p>History: Kadek was found straying around Pandan Crescent. Because of his small stature, he was often bullied by the other strays. After he was caught and sterilised, his feeder decided to try to rehome him rather than releasing him.</p>","admin","2018-07-15"),
("Soju","A","","M","2015-05-01","Cross Breed","","1","1","1","0","soju.jpg","<p>Description: Soju is an active and friendly boy who gets along with other dogs and people. He was initially wary of people but not anymore. In fact, he loves attention now and will follow people everywhere.</p>
<p>History: Soju was found at a void deck in Sembawang without any sibling or mother in sight. Suspected to be abandoned and fearing that he would not be able to fend for himself, he was rescued by a kind lady.&nbsp;</p>","admin","2018-07-15"),
("Tuassie","A","","F","2013-08-01","Cross Breed","","1","1","1","1","tuassie.jpg","<p>Description: Tuassie is a friendly and playful girl.</p>
<p>History: Tuassie was a stray from Tuas who was caught and impounded by the authorities.</p>","admin","2018-07-15"),
("Sterling","A","","M","2013-01-01","Cross Breed","","1","1","1","1","sterling.jpg","<p>Description: Sterling is super friendly and affectionate towards people. He is playful and active and is better with female dogs.&nbsp;</p>
<p>History: Sterling was a stray from Sungei Kadut who was caught by the authorities and subsequently offered to animal welfare groups for rehoming because of his good temperament.</p>","admin","2018-07-15"),
("Louisa","A","","F","2015-10-01","Cross Breed","","1","1","1","0","louisa.jpg","<p>Description: Louisa might be a little shy at first but is a friendly and affectionate girl once she knows you.</p>
<p>History: Louisa was rescued as a 2 month puppy together with her 2 siblings in the Lim Chu Kang area.</p>","admin","2018-07-15"),
("Lambert","A","","M","2015-10-01","Cross Breed","","1","1","1","1","lambert.jpg","<p>Description: Lambert needs a little time to warm up but once he does, he enjoys cuddles and attention.</p>
<p>History: Lambert was rescued as a 2 month puppy together with his 2 siblings in the Lim Chu Kang area.&nbsp;</p>","admin","2018-07-15"),
("Chi Chi","A","","M","2013-06-01","Cross Breed","","1","1","1","1","chichi.jpg","<p>Description: Chi Chi is independent, affectionate and very low maintenance. He is good with children, loves swimming and walks well on leash.</p>
<p>History: Chi Chi was rescued from an abusive family.</p>","admin","2018-07-15"),
("Jordan","A","","M","2014-12-01","Cross Breed","","1","1","1","0","jordan.jpg","<p>Description: Although a little reserved, Jordan is very sweet. Initially shy around strangers, it doesn\'t take long for him to warm up but he needs some some space and patience while getting to know someone new, as well as a calm presence when out on walks.&nbsp;</p>
<p>History: Jordan was a stray on Jurong Island who was badly attacked by several other dogs and almost died from blood lost. He has since recovered and is doing well.</p>","admin","2018-07-15"),
("Snapper","A","","M","2008-01-01","Cross Breed","","1","1","1","1","snapper-1147.jpg","Description: Snapper is shy with strangers but will warm up. He is independent and loyal and walks quite well on leash.
History: Snapper was rescued from a hoarder.","admin","2018-07-15"),
("Prada","A","","M","2013-08-01","Cross Breed","","1","1","1","0","prada-1151.jpg","Description: Prada is an extremely mild mannered dog who can get along with almost everyone, people as well as dogs. He walks well on leash but can be a little skittish in heavy traffic.
History: Prada and his brother Gucci were born to a stray mother living at a factory in Tuas.","admin","2018-07-15"),
("Sweetheart","A","","F","2011-01-01","Cross Breed","","1","1","1","1","sweetheart-1152.jpg","Description: Sweetheart is a loving girl who enjoys playing with toys. She takes a little time to warm up to strangers but once on leash, she follows. She is good on walks and is indoor and grass trained.
History: Sweetheart was rescued when she was heavily pregnant. She gave birth to 10 pups at the vet, most of whom have been rehomed.","admin","2018-07-15"),
("Xiaotiantian","A","","F","2011-06-01","Cross Breed","","1","1","1","1","xiaotiantian-1174.jpg","Description: Xiaotiantian has a sweet disposition and is relatively low energy. She is a well behaved girl who likes human contact.
History: Xiaotiantian was a stray from a factory in Lim Chu Kang.","admin","2018-07-15"),
("Christmas","A","","F","2014-08-01","Cross Breed","","1","1","1","1","christmas-1256.jpg","Description: Christmas is a shy but friendly girl. The fact that she only has 3 usable legs doesn’t faze her and she can run, jump and climb with no difficulty whatsoever!
History: Christmas was found in Seletar with a mangled front left paw just before Christmas in 2015. We suspect that she had her leg caught in a wild boar trap. We decided against amputating her whole leg and Christmas now wears a soft shoe when she goes on walks to protect her paw.","admin","2018-07-15"),
("Fee Fee","A","","M","2013-08-01","Cross Breed","","1","1","1","1","fee-fee-1261.jpg","Description: Fee Fee is a sweet natured and responsive boy who loves nothing more than to be shown affection. He is calm and walks well on leash. He is independent and is contented just to chill by himself.
History: Fee Fee was a stray in Tuas who fell victim to the dreaded disease distemper. He was rescued to be treated and has fully recovered.","admin","2018-07-15"),
("Asher","A","","M","2014-03-01","Cross Breed","","1","1","1","1","asher-1273.jpg","Description: Asher is sweet and friendly towards people. He loves affection and attention and is best suited to a family who can be at home with him.
History: Asher was rescued from a construction site.","admin","2018-07-15"),
("Dumbo","A","","M","2013-01-01","Cross Breed","","1","1","1","1","dumbo-1351.jpg","<p>Description: Dumbo was so named because as a puppy, his ears were humongous! This adorable boy is good natured, easy going and quiet. History: Dumbo was born at a heavy vehicles factory. He was supposed to be sterilised and released but because of his sweet and friendly nature, the caretakers at the boarding kennel offered to house him until he found a home.</p>","admin","2018-07-15"),
("Hector","A","","M","2012-01-01","Cross Breed","","1","1","1","1","hector-1353.jpg","Description: Hector has a minor handicap. Due to the damage caused by distemper to his nervous system, he suffers from twitching and can only use the left side of his body. However, Hector is a strong boy and has been coping well with his handicap. He is able to hop about and does his business like a normal dog. Hector is now on supplements to stabilise his brain functions and he needs to be on hydrotherapy once a week to strengthen the left side of his body. He is a friendly boy and is good with female and smaller size dogs.
History: When Hector was 3 months old, he was found with a torn ear and sent to the vet for treatment. While at the clinic, he was tested positive for distemper and was also malnourished. He was quarantined at the vet clinic for 4 months before being transferred to a boarding kennel. Hector has since fully recovered from distemper and has been waiting for a home since 2013.","admin","2018-07-15"),
("Chaplin","A","","M","2016-03-01","Cross Breed","","1","1","1","1","chaplin-1357.jpg","<p>Description: Chaplin is super interested in everything... pebbles, leaves, snails, twigs, plastic bags, trees, birds, cats, cars, people... you get the picture? He is affectionate and loving, loves his food and his cushioned cot. He\'s boisterous and rough at play especially with his sister, Ciara. Chaplin can be quite unaware of dangers. He\'ll try everything once and if he can get away with it, he\'ll persist until the next thing... hence, he needs to be disciplined with what\'s not acceptable. Chaplin needs regular walks and he is use to doing his business outside. History: Chaplin was part of a litter of stray puppies living in a cemetery. He was found with a huge maggot wound on his back which has since healed.</p>","admin","2018-07-15"),
("Hua Hua","A","","F","2010-12-01","Cross Breed","","1","1","1","0","hua-hua-1418.jpg","<p>Description: Hua Hua is an outgoing, confident, friendly and independent girl who walks well on leash. She is curious and loves to explore her surroundings with her handler. She takes time to warm up to new dogs History: Hua Hua used to live a happy and carefree life with her siblings at a cemetery until someone cruelly carried out a horrible mass poisoning at her site. Hua Hua and her siblings were critically ill and only she and her brother pulled through. Her other 2 siblings sadly did not make it. Hua Hua has made a full recovery and has been waiting for a home in a commercial kennel for many years.</p>","admin","2018-07-15"),
("Audemars","A","","F","2016-11-01","Cross Breed","","1","1","1","0","audemars-1419.jpg","Description: Shy at first, Audemars can be playful, lively and sociable once warmed up. She likes to play with her water bowl.
History: Audemars was rescued with her 6 siblings from a factory in Tuas.","admin","2018-07-15"),
("Chopard","A","","F","2016-11-01","Cross Breed","","1","1","1","0","chopard.jpg","Description: Chopard is good with people, adults and children alike. Although she has a wobbly right hind leg, her health seems fine otherwise.
History: ","admin","2018-07-15"),
("Terry","A","","M","2014-10-01","Cross Breed","","1","1","1","1","terry-1442.jpg","Description: Terry is a sweet and shy boy who can be unsure of new faces. Terry is always eager for his walks but can be quite laid back and gentle at other times of the day, happy with idling on his own.
History: Terry was found alone in a factory in Tuas when it closed down.","admin","2018-07-15"),
("Siao Hei","A","","M","2013-08-01","Cross Breed","","1","1","1","1","siao-hei-1492.jpg","Description: Siao Hei is a sweet and very petite boy who is well behaved and walks well on leash. Because of his kidney issues, Siao Hei would need to be on a low protein diet and require once or twice weekly subcutaneous fluid therapy.
History: Siao Hei was rescued from a factory when the workers there noticed he was not eating but drinking a lot of water. He was diagnosed as having mild kidney failure.","admin","2018-07-15"),
("Kathi Boy","A","","M","2015-06-01","Cross Breed","","1","1","1","0","kathi-boy-1493.jpg","Description: Kathi Boy is good with humans and dogs. He loves walks and receiving pats from people. He is paper and grass trained.
History: Kathi Boy was a hungry stray who came to a factory in Tuas looking for food and was rescued.","admin","2018-07-15"),
("Enzo","A","","M","2017-02-01","Cross Breed","","1","1","1","0","enzo-1495.jpg","Description: Enzo was very shy when he was first rescued but has since earnt to crave for hugs and attention from humans.
History: Enzo was a stray puppy who was looked after by a cemetery caretaker.","admin","2018-07-15"),
("Xiao Hei","A","","M","2009-01-01","Cross Breed","","1","1","1","0","xiao-hei-1498.jpg","Description: Xiao Hei is a very friendly boy and despite his age, acts like a happy and excitable puppy when he’s around people he is familiar with.
History: Xiao Hei was rescued from the Brickland Road area after his leg was injured by a wild boar trap.","admin","2018-07-15"),
("Tully","A","","M","2017-02-01","Cross Breed","","1","1","1","0","tully-1499.jpg","Description: Tully is a playful boy but quite wary when he meets new people.
History: Tully was a stray puppy who was looked after by a cemetery caretaker.","admin","2018-07-15"),
("Freda","A","","F","2017-06-01","Cross Breed","","1","1","1","0","freda-1503.jpg","Description: Freda is sweet but very shy girl who takes some time to warm up. She is very playful and loves being with other dogs. She will be suitable for a family who has an older dog in the house to mentor her.
History: Freda and her siblings were born to a stray mother around the Fishery Port Road area.","admin","2018-07-15"),
("Milo","A","","M","2017-06-01","Cross Breed","","1","1","1","0","milo-1504.jpg","Description: Milo loves people. He will always approach you with a waggy tail even for just a few seconds of attention. He is a cheerful and trusting puppy who doesn’t mind being hugged and touched even while he is sleeping.
History: Milo was rescued with his sister from Jalan Lekar where his stray mother resided with a pack of dogs.","admin","2018-07-15"),
("Nami","A","","F","2014-01-01","Cross Breed","","1","1","1","1","nami-1528.jpg","Description: Nami is a gorgeous girl who takes time to warm up to people. Following her recovery from a wire-trap injury, she has slowly emerged from her shell and become more sociable. She is very chill and enjoys leisurely walks.
History: Nami was a stray in Lim Chu Kang who was badly injured by a wire trap.","admin","2018-07-15"),
("Tao Bao","A","","F","2017-05-01","Cross Breed","","1","1","1","0","tao-bao-1532.jpg","Description: Tao Bao was shy with people but great with other dogs. Once warmed up, she is affectionate yet independent.
History: Tao Bao was caught accidentally when she walked into a trap laid for her mother as part of a TNR (trap-neuter-release) programme.","admin","2018-07-15"),
("Karen","A","","F","2012-01-01","Cross Breed","","1","1","1","0","karen-1537.jpg","Description: Karen is a sweet and very affectionate girl who loves everyone and is good with other dogs. Call her and she will walk up to you with a smile plastered on her face. Give her a scratch on her head and you’ve got yourself a shadow who will follow you around. She enjoys her baths and her walks!
History: Karen was born at Tuas South, one out of a litter of four. She resided in the parking area of a huge shipyard where she was friendly with the workers. Unfortunately when Karen was around 3 years old, she was caught and impounded by the authorities due to complaints about her excessive barking towards strangers.","admin","2018-07-15"),
("Fin","A","","M","2017-06-01","Cross Breed","","1","1","1","0","fin-1567.jpg","Description: Fin is playful and friendly and in the midst of learning how to walk on leash. He is both pee pad and grass trained.
History: Fin and his siblings were rescued from Tuas where they were desperately looking for food.","admin","2018-07-15"),
("Eevee","A","","F","2017-05-01","Cross Breed","","1","1","1","1","eevee-1569.jpg","Description: Eevee is a very sweet, affectionate and petite girl. She is generally good with other dogs but will get a little jealous and want her share of attention if you spend too much time with another dog. She walks pretty well on leash but has a tendency to hop around like a kangaroo when in grassy areas!
History: Eevee was rescued from under a lorry when she was a very young puppy.","admin","2018-07-15"),
("Minion","A","","F","2016-01-01","Cross Breed","","1","1","1","1","minion-1570.jpg","Description: Minion is a low energy, calm, submissive and shy dog who takes a little time to warm up to people. She is an easily contented dog who is satisfied to have a roof over her head, warm meals and slow walks. She loves to be clean so will do her business outside.
History: Minion was a stray young mother who was recused after she was involved in an accident at a construction site. She was in much in pain when she limped to her feeders for help. Her pelvis was cracked and her left hind leg was fractured. The accident also caused her to lose her sight in her right eye. But with her strong will, her condition continued to improve day by day and now she has recovered under her fosterer\'s care though she only uses 3 legs to walk and run.","admin","2018-07-15"),
("Tricks","A","","M","2013-04-01","Cross Breed","","1","1","1","0","tricks-1571.jpg","Description: Tricks has a beautiful coat and an intense gaze. He enjoys the company of people and will lie down for rubs and to play. Tricks tends to be mouthy but he doesn’t mean any harm. He has a towel at the shelter that he enjoys chewing and tugging. Because of his background, some time and patience to get to know his quirks would be useful. He will show displeasure by growling.
History: Tricks was from a container yard in Penjuru and was chained up as he liked to chase people and cars. He was bitten by a pack of dogs that came into the yard one day and the wound worsened to the point that he had to have his hind leg amputated.","admin","2018-07-15"),
("Yoko","A","","F","2012-07-01","Cross Breed","","1","1","1","1","yoko-1572.jpg","Description: Give Yoko enough time and attention, and she will likely warm up to you. She is a bit wary of strangers and will not approach them, but is friendly and more playful around people she knows. The lovely lady also enjoys having her own space for some me-time.
History: Yoko was among several dogs and puppies at Yishun Park that were rounded up by the AVA.","admin","2018-07-15"),
("Joe","A","","M","2010-05-01","Cross Breed","","1","1","1","0","joe-1574.jpg","Description: Joe is missing a hind leg but this has not stopped him from enjoying walks and being outdoors. Joe has some food aggression and may not be friendly to everyone, but he has mellowed over the years. To those he strikes a connection with, he is extremely sweet, enthusiastic and loyal. This special boy has gorgeous, soulful eyes.
History: Joe was rescued in March 2012, a victim of an llegal wild boar trap in the vicinity of Old Jurong Road. By the time he was discovered, severe infection had already set in and his leg had to be amputated. However he was also found to be heartworm positive so his surgery had to be delayed until he recovered.","admin","2018-07-15"),
("Cha Cha","A","","F","2014-01-01","Cross Breed","","1","1","1","1","cha-cha-1575.jpg","Description: Cha Cha is a sweet girl who is happy to have others as the centre of attention. She is shy but will warm up with time and make a lovely companion. She has also become slightly more playful after being paired with a more active and sociable dog at the kennels.
History: Cha Cha was a member of a friendly pack of strays residing at Sungei Buloh Nature Reserve. Unfortunately visitors issued a complaint so they were forced to be removed.","admin","2018-07-15"),
("Lola","A","","F","2012-01-01","Cross Breed","","1","1","1","0","lola-1576.jpg","Description: Lola is initially shy but lights up when she sees people she is familiar with. A gentle approach is best when getting to know this lovable and charming lady. Lola is unfussy and fairly independent.
History: Lola was an unsterilised stray female in the Lim Chu Kang area who was attracting a lot of unwanted attention from the stray male dogs. The owner of one of the farms there threaten to catch and dispose of her as the male dogs were ruining the vegetation while chasing her.","admin","2018-07-15"),
("Tau Sar","A","","M","2014-10-01","Cross Breed","","1","1","1","0","tau-sar-1577.jpg","Description: Tau Sar and his kennel mate Leen Yong are the big, macho boys of the shelter. They look slightly intimidating and play and wrestle with each other the way boys do, but are actually very friendly and sociable. Tau Sar will beckon you to enter the kennel with inquisitive eyes and stay still for pats. He enjoys walks and, with his short and distinctive dark brown coat, will be a handsome and low-maintenance addition to the family.
History: Tau Sar was a stray who was caught by the authorities and subsequently offered to animal welfare groups for rehoming because of his good temperament.","admin","2018-07-15"),
("Leen Yong","A","","M","2013-10-01","Cross Breed","","1","1","1","0","leen-yong-1578.jpg","Description: Leen Yong and his kennel mate Tau Sar are the big, macho boys of the shelter. They look slightly intimidating and play and wrestle with each other the way boys do, but are actually friendly and warm up quickly to humans. Leen Yong is the slightly more playful one. He hurries out of his “room” in the kennel when people enter and loves treats and walks/runs.
History: Leen Yong was a stray who was caught by the authorities and subsequently offered to animal welfare groups for rehoming because of his good temperament.","admin","2018-07-15"),
("Clovis","A","","M","2016-02-01","Cross Breed","","1","1","1","0","clovis-1583.jpg","Description: Clovis is the friendliest of of the 3 scared and skittish brothers. He is the one that most readily approaches people to sniff them and to take treats. Clovis is now full-grown and has shared some of his youthful vitality with his older kennel-mate Nature. He is still quite skittish and would benefit from a patient and calm presence, including when out on walks.
History: Clovis and his 2 brothers were rescued from Jurong Island when they were puppies.","admin","2018-07-15"),
("Calbee","A","","F","2017-07-01","Cross Breed","","1","1","1","1","calbee-1587.jpg","Description: Calbee is very food motivated. Although she is good with other dogs, she is very shy with people and will need time and patience. She is peepad trained, has no aggression and walks well on leash.
History: Calbee was a stray from a factory in Tuas who was caught for TNR but because of her sweet disposition, we decided to try to rehome her.","admin","2018-07-15"),
("Luke","A","","M","2013-01-01","Cross Breed","","1","1","1","0","luke-1589.jpg","Description: Luke is very friendly toward people and walks well on leash. He is quite a chill, easy going and independent boy.
History: Luke was a stray from the Lim Chu Kang area who was often bullied by the other dogs in his pack. His spate of bad luck continued when he was caught by the authorities but fortunately for him, his feeder noticed that he was missing and contacted us to claim him from the pound.","admin","2018-07-15"),
("Marley","A","","M","2017-03-01","Cross Breed","","1","1","1","1","marley-1591.jpg","Description: Marley is happy to play alone with his toys as he’s totally independent. Once he warms up and trusts you he’ll stick his head on your lap for some love or ask you to play fetch with his ball. He can be as active or as lazy as you want. Making him a great pacemaker as your jogging buddy or your personal guard dog, keeping you company as you work on your computer in the evenings. He is super food motivated and super smart, which makes him very trainable. But needs someone with experience and patience to handle him as he\'s not friendly towards other dogs. He is both paper and grass-trained. He has no separation anxiety. However, he needs to be walked in the morning and evenings.
History: Marley was originally from a factory in Mandai but because it was going to be razed, a kind hearted driver decided to relocate him to a worksite in Jalan Lekar. Unfortunately Markey met with an accident at the new location and broke his leg. He had to undergo a costly and long drawn surgery but thankfully has recovered very well and can now walk, run and jump with no issues.","admin","2018-07-15"),
("Blackie","A","","M","2012-05-01","Cross Breed","","1","1","1","0","blackie-1596.jpg","Description: Blackie is a super friendly and confident boy who loves head pats. He is generally a calm dog who likes slow walks but is nervous when there is lightning and thunder. Although missing his front right paw, Blackie does not act like a handicapped dog.
History: Blackie was staying at a factory in Tuas South but when the company relocated, he was left behind. His rescuer has no idea how he lost his front right paw. She thinks it could either be caused by an accident or an illegal wild boar trap.","admin","2018-07-15"),
("Da Fu","A","","F","2013-11-01","Cross Breed","","1","1","1","1","da-fu-1597.jpg","Description: Da Fu is an extremely small local cross breed, the size of a corgi. She is sweet and gentle but a little shy.
History: Da Fu was abandoned by her rescuer at a boarding kennel.","admin","2018-07-15"),
("Harry","A","","M","2012-11-01","Cross Breed","","1","1","1","0","harry-1598.jpg","Description: Harry is very friendly and is always excited and happy to meet people.
History: Harry was abandoned by his rescuer at a boarding kennel.","admin","2018-07-15"),
("Nugget","A","","M","2014-06-01","Cross Breed","","1","1","1","0","nugget-1599.jpg","Description: Nugget is an effervescent, excitable and friendly boy who can sometimes get over excited. He enjoys his walks but would need to be guided on leash.
History: Nugget was rescued as puppy.","admin","2018-07-15"),
("Ron","A","","M","2014-04-01","Cross Breed","","1","1","1","0","ron-1600.jpg","Description: Ron is gentle and a little shy but friendly towards people. He enjoys walks but needs coaxing sometimes when on the leash.
History: Ron was abandoned by his rescuer at a boarding kennel.","admin","2018-07-15"),
("Mei Mei","A","","F","2011-03-01","Cross Breed","","1","1","1","1","mei-mei-1601.jpg","Description: Mei Mei is a calm girl who loves company and enjoys walks.She sustained an injury to her right front leg before she was rescued and now walks with a limp.
History: Unknown","admin","2018-07-15"),
("Bambi","A","","F","2011-02-01","Cross Breed","","1","1","1","0","bambi-1615.jpg","Description: Bambi is a shy girl who takes a little while to warm up. She is a big baby who loves soft toys and towels but is scared of storms and cars. She enjoys walks (she currently goes on a short walk in the morning and a long walk at night) and rolling on grass.
History: Bambi was adopted when she was around a year old by a family who kept her outdoors on their landed property. In Sept 2016, someone found her wandering at a park and posted a “found” notice on Facebook. Bambi’s rescuer recognised her and went to collect her. When approached, her adopter claimed that Bambi had escaped and did not want her back.","admin","2018-07-15"),
("Sakae","A","","M","2016-03-01","Cross Breed","","1","1","1","1","sakae-1617.jpg","Description: When Sakae was first rescued, he was extremely timid and would shy away from human contact. Now, whilst still shy with strangers, Sakae has transformed into an affectionate, curious boy who will display his playful side once he warms up. His comical and quizzical expressions add to his charm. If yours is a family with adults or teenagers, with the patience to allow him time to settle in, Sakae will be a fun addition to your family.
History: Sakae was rescued from a factory in Senoko in an appalling state when he was only 7 months old. He was severely malnourished and tick-infested.","admin","2018-07-15"),
("Jade","A","","F","2011-08-01","Cross Breed","","1","1","1","1","jade-1619.jpg","Description: Jade is a quiet and calm girl who enjoys walks. She is very good on the leash and warms up easily to new faces.
History: Jade was born in a factory but was rescued as a puppy and housed in a kennel since then.","admin","2018-07-15"),
("Pebble","A","","F","2011-08-01","Cross Breed","","1","1","1","0","pebble-1620.jpg","Description: Pebble is an independent gal but loves the company of people. She still needs some training on her leash walking.
History: Pebble was born in a factory but was rescued as a puppy and housed in a kennel since then.","admin","2018-07-15"),
("Flint","A","","M","2011-08-01","Cross Breed","","1","1","1","0","flint-1621.jpg","Description: Flint is an independent and low maintenance dog who loves human companionship. He walks well on leash and enjoys his walks.
History: Flint was born in a factory but was rescued as a puppy and housed in a kennel since then.","admin","2018-07-15"),
("Kimmy","A","","F","2018-03-01","Cross Breed","","1","1","1","0","kimmy-1622.jpg","Description: Kimmy is a sweet but shy little girl but once she has warmed up, she is happy and loving.
History: Kimmy is one of a litter of 4 puppies from a factory in Tuas South.","admin","2018-07-15"),
("Horatio","A","","M","2017-10-01","Cross Breed","","1","1","1","0","horatio-1631.jpg","Description: Horatio is a very sweet, gentle and lovable boy but needs time to warm up to his surroundings. He likes to be hugged at times but dislikes baths or having his nails clipped though he is fine to be cleaned with wet tissues. If he dislikes you touching certain areas, he will use his paws to push your hands away. A habit of his is to ""bite/nip"" fingers as a form of playing. Horatio has always been in the company of other dogs so he might have some separation anxiety when left alone. On walks, Horatio will pull a little in the beginning but will settle into a rhythm though he can be wary and excitable in new surroundings so he will need some assurance. Horatio enjoys his food so do not leave any food unattended as he will steal it! Horatio is pee pad trained.
History: Horatio was rescued as a very young puppy along with his siblings.","admin","2018-07-15"),
("Robin","A","","M","2017-01-01","Cross Breed","","1","1","1","1","robin-1632.jpg","Description: Robin is good with people and tends to form a tight bond with his caregiver. However he can be mischievous in the company of other dogs. He walks well on leash and enjoys roaming.
History: Robin as a stray from the Lim Chu Kang area who was caught by the authorities but fortunately for him, his feeder noticed that he was missing and contacted us to claim him from the pound. Robin was found to be heartworm positive but has since undergone treatment.","admin","2018-07-15"),
("Maka","A","","M","2012-05-01","Cross Breed","","1","1","1","0","maka-1635.jpg","Description: Maka is of a unique breed, offspring of a Pedigree wildboar hunting line from Louisiana. Maka loves long runs, hikes and playing with his handler. He is quick and agile, a fast learner that thrives in play and dog obedience. He has not lived with other dogs and needs to be under close supervision with children. He will thrive under a firm handler and loving family.
History: Maka came to Singapore from Hawaii 4 years ago. He has had a single owner from the time he was a puppy. His owner is unable to provide the care Maka needs due to work commitments and frequent travelling.","admin","2018-07-15"),
("Emma","A","","F","2018-06-01","Cross Breed","","1","1","1","0","emma-1714.jpg","Description: Emma needs time to warm up to strangers and other dogs but once she is comfortable, she can be active, playful and cheeky. She is fine with big and small dogs and cats as well. She is very food motivated and is fully paper trained. Emma needs a patient and experienced family, preferably without young children, who will nurture and instil confidence in her as her insecurity can lead to fear aggression if not kept in check.
History: Emma and her 5 siblings were rescued (together with their mother) from a shipyard at Benoi Road when they were only a few days old.","admin","2018-07-15"),
("Biru","A","","M","2015-06-01","Cross Breed","","1","1","1","0","biru-1715.jpg","<p>Description: Biru is a slightly chubby, curious and sweet boy who welcomes any human with a smiling face. He is always up for a good scratch behind his ears but can also be a relaxed and independent dog. He walks well on leash and prefers to go at a comfortable strolling pace. History: Biru was rescued with his mother from a factory at Jalan Buroh. The company had vacated and locked up the premises, leaving these 2 dogs behind. Food and water had to be slotted through a hole in the fence for more than a week before the person in charge could be located to unlock the gate for the dogs to be rescued.</p>","admin","2018-07-15"),
("Patani","A","","F","2013-06-01","Cross Breed","","1","1","1","0","patani-1716.jpg","Description: Patani is a calm, motherly figure to her son and kennel mate Biru. She is very good natured, sociable and enjoys relaxing with people. She does well on leash and is easy on walks, preferring a slow stroll with her human.
History: Patani was rescued with her son from a factory at Jalan Buroh. The company had vacated and locked up the premises, leaving these 2 dogs behind. Food and water had to be slotted through a hole in the fence for more than a week before the person in charge could be located to unlock the gate for the dogs to be rescued.","admin","2018-07-15"),
("Hank","A","","M","2012-10-01","Cross Breed","","1","1","1","0","hank-1717.jpg","Description: Hank is very friendly with people although he takes a little time to warm up to some ladies. Super soppy once he’s used to you and will demand ear scratches and belly rubs regularly. He’s physically very strong and will need an equally strong owner but he doesn’t pull on a leash and is well behaved. He seems to tire easily, probably because he hasn’t been exercised much in the past, and will flop at your feet as soon a walk is finished! Hank can be quite vocal and may hump humans.
History: Hank and his brother Tank were confined in a small space at a factory in Kaki Bukit.","admin","2018-07-15"),
("Tank","A","","M","2012-10-01","Cross Breed","","1","1","1","0","tank-1718.jpg","Description: Tank is a little more reserved than his brother Hank but is still very friendly with strangers and loves interacting with humans, especially when they walk past his kennel. He is physically similar to Hank, although a bit smaller - he will require an owner who can handle big strong dogs. He’s also well behaved although he can pull a little on the leash. He’s a mellow soul who likes his own space to chill out alone from time to time. Tank can bark quite a bit when by himself, and may hump humans.
History: Tank and his brother Hank were confined in a small space at a factory in Kaki Bukit.","admin","2018-07-15"),
("Wolfie","A","","F","2016-09-01","Cross Breed","","1","1","1","1","wolfie-1719.jpg","Description: Wolfie is gorgeous, excitable, a little hyperactive and very sociable. She loves attention and affection and for people to play with her. Although she is very fun to be around and has a lovely sunny personality, young Wolfie will need someone who is not afraid to enforce a bit of discipline, for instance when it comes to walks and nibbling of people\'s hands.
History: Wolfie was a stray who was caught by the authorities and subsequently offered to animal welfare groups for rehoming because of her good temperament.","admin","2018-07-15"),
("Woody","A","","M","2017-05-01","Cross Breed","","1","1","1","1","woody-1720.jpg","Description: Handsome Woody is a sweet boy who is shy around new faces. Once he warms up, he can be affectionate, curious, goofy and playful. He enjoys his walks and loves treats. If yours is a family with the patience to allow him to settle in, Woody will be a fun addition to your family.
History: Woody was born at Woodlands Industrial Park where the condition was extremely filthy and dusty.","admin","2018-07-15"),
("Otis","A","","M","2017-08-01","Cross Breed","","1","1","1","0","otis-1721.jpg","Description: Otis is a shy and gentle dog who takes awhile to approach new faces. He is calm at home and low maintenance so he will generally choose his spot and stay there till his fosterer returns. He is also grass trained, friendly with other dogs and generally enjoys his walk with another foster dog.
History: Otis and his 2 siblings were rescued as puppies from a drain beside a nature reserve.","admin","2018-07-15"),
("Goma","A","","F","2018-01-01","Cross Breed","","1","1","1","1","goma-1722.jpg","Description: Goma is a sweet, gentle and petite girl who answers to her name and walks well on leash. She is good with children, cats and other dogs, passively submitting to more dominant dogs.
History: Goma was rescued as a 3 month old puppy from Sungei Gedong. Besides being malnourished and feverish, she also had bite wounds on the underside of her belly and one of her front legs and two of her back legs were fractured! The front and the back left legs healed well by themselves but her right hind leg needed surgery as the bone was infected. In the midst of all this, we also found out that she had babesia (a form of tick fever)! Goma has been treated for all her ailments and has now fully recovered.","admin","2018-07-15"),
("Sheba","A","","F","2017-03-01","Cross Breed","","1","1","1","1","sheba-1723.jpg","Description: Sheba is a pretty and petite Shiba Inu lookalike. She is totally at ease with people and is loving and trusting. She loves food, treats and toys. Sheba is a confident dog and enjoys playing with other dogs but tends to want to dominate other dogs by attempting to mount them. She would be better in a single dog household as she tends to get jealous and will fight for attention when another dog is around. She is grass trained and needs at least 2 walks a day. Sheba will thrive with an experienced family who will be patience and firm but gentle with her.
History: Sheba was a stray who was caught by the authorities and subsequently offered to animal welfare groups for rehoming because of her good temperament.","admin","2018-07-15"),
("Beige","A","","M","2018-10-01","Cross Breed","","1","1","1","0","beige-1724.jpg","Description: Beige is very friendly, very boisterous and very active. He is good with cats and dogs and is litter tray trained.
History: Beige and his 8 siblings were born to a stray mother at a construction site at Neo Tiew Crescent. They were taken in as they almost drowned during the monsoon season.","admin","2018-07-15"),
("Green","A","","M","2018-10-01","Cross Breed","","1","1","1","0","green-1725.jpg","Description: Green is very friendly, very boisterous and very active. He is good with cats and dogs and is litter tray trained.
History: Green and his 8 siblings were born to a stray mother at a construction site at Neo Tiew Crescent. They were taken in as they almost drowned during the monsoon season.","admin","2018-07-15"),
("Blue","A","","M","2018-10-01","Cross Breed","","1","1","1","0","blue-1726.jpg","Description: Blue is very friendly, very boisterous and very active. He is good with cats and dogs and is litter tray trained.
History: Blue and his 8 siblings were born to a stray mother at a construction site at Neo Tiew Crescent. They were taken in as they almost drowned during the monsoon season.","admin","2018-07-15"),
("Ricco","A","","M","2017-08-01","Cross Breed","","1","1","1","0","ricco-1727.jpg","Description: Ricco is a playful and affectionate boy who is human and dog friendly. Although only recently rescued, he has already learn to walk on leash and is pee pad and grass trained.
History: Ricco was rescued from a factory where he saw his brother being hit by a lorry. The brother was seriously injured and both went into hiding because they were traumitised by the incident. Sadly, his brother succumbed to his injuries and passed on a few days later leaving Ricco to fend for himself.","admin","2018-07-15"),
("Ummi","A","","F","2015-11-01","Cross Breed","","1","1","1","1","ummi-1728.jpg","Description: Ummi is a low maintenance, gentle, calm and quiet girl. An ideal family for Ummi would be one with adults and older children (if any) who has the patience to let her settle in and open up at her own time and pace. She is gaining confidence outdoors and is beginning to enjoy her walks.
History: Ummi was a stray from Tuas who was rescued together with her daughter.","admin","2018-07-15"),
("Omin","A","","F","2018-05-01","Cross Breed","","1","1","1","1","omin-1729.jpg","Description: Omin is quiet, super sweet and a little shy. She is good with other dogs and highly food motivated! Omin is grass trained and walks very well on leash.
History: Omin was a stray living with her siblings at a cemetery and was caught to be sterilised and released as part of our TNRM programme. However due to her pleasant temperament, we decided to rehome her instead of releasing her back.","admin","2018-07-15"),
("Nacho","A","","M","2018-10-01","Cross Breed","","1","1","1","0","nacho-1730.jpg","Description: Nacho is a loving and loyal boy who will follow his caregiver around. He is intelligent and a fast learner and has learnt to sit and wait for his food and treats. Nacho is a sociable puppy and is good with people and other dogs. He walks well on leash and does his business on pee pads, newspapers or outdoors.
History: Nacho was found alone at Jalan Lekar without any mother or siblings in sight.","admin","2018-07-15"),
("Mario","A","","M","2018-10-01","Cross Breed","","1","1","1","0","mario-1731.jpg","Description: Mario is confident, intelligent and sociable and is the alpha amongst his siblings.
History: Mario and his siblings were living under rough conditions at a construction waste recycling plant in Lim Chu Kang and were very malnourished when they were rescued.","admin","2018-07-15"),
("Dino","A","","M","2018-10-01","Cross Breed","","1","1","1","0","dino-1732.jpg","Description: Dino was living in his bigger brother’s shadow at first but is now coming into his own. He is active and friendly towards people.
History: Dino and his siblings were living under rough conditions at a construction waste recycling plant in Lim Chu Kang and were very malnourished when they were rescued.","admin","2018-07-15"),
("Naomi","A","","F","2018-01-01","Cross Breed","","1","1","1","1","naomi-1733.jpg","Description: Naomi is a lovable and petite girl who is very cheerful and active like a young puppy when indoors. She is more timid when outside and is still learning to walk on leash. She is more comfortable walking on pavements and would need a little coaxing when walking on the road. She is very food motivated and not fussy about what she eats. Naomi is paper trained and will be good for a first time dog owner who can shower her with love as she loves human attention.
History: Naomi was a stray mother at a construction site at Neo Tiew Crescent who gave birth to a litter of 9 puppies. The whole family was taken in as they almost drowned during the monsoon season.","admin","2018-07-15"),
("Bliss","A","","F","2018-06-01","Cross Breed","","1","1","1","1","bliss-1734.jpg","Description: Bliss is very friendly and active and has obviously not outgrown her puppy behaviour. She should not be left alone for too many hours as a young dog like her would likely be destructive when bored. Bliss is an intelligent girl and would thrive under a firm and patient adopter who can guide and train her.
History: Bliss was a stray living with her sister at Jalan Lekar and was caught to be sterilised and released as part of our TNRM programme. However due to her pleasant temperament, we decided to rehome her instead of releasing her back.","admin","2018-07-15"),
("Bless","A","","F","2018-06-01","Cross Breed","","1","1","1","1","bless-1735.jpg","Description: Bless is very friendly and active and has obviously not outgrown her puppy behaviour. She should not be left alone for too many hours as a young dog like her would likely be destructive when bored. Bless is an intelligent girl and would thrive under a firm and patient adopter who can guide and train her.
History: Bless was a stray living with her sister at Jalan Lekar and was caught to be sterilised and released as part of our TNRM programme. However due to her pleasant temperament, we decided to rehome her instead of releasing her back.","admin","2018-07-15"),
("Titus","A","","M","2017-11-01","Cross Breed","","1","1","1","0","titus-1736.jpg","Description: Titus is a friendly and sociable puppy who is adaptable and a fast learner.
History: Titus is one of a litter of 5 puppies born to a stray mother in Tuas.","admin","2018-07-15"),
("Tyler","A","","M","2017-11-01","Cross Breed","","1","1","1","0","tyler-1737.jpg","Description: Tyler is a friendly and sociable puppy who is adaptable and a fast learner.
History: Tyler is one of a litter of 5 puppies born to a stray mother in Tuas.","admin","2018-07-15"),
("Thelma","A","","F","2017-10-01","Cross Breed","","1","1","1","0","thelma-1738.jpg","Description: Thelma is bold, outgoing and affectionate with people. She tends to be a little rambunctious with other puppies.
History: Thelma and her siblings were caged up by workers after their mother was tragically knocked down by a truck in Tuas.","admin","2018-07-15"),
("J.D.","A","","M","2018-10-01","Cross Breed","","1","1","1","0","jd-1739.jpg","Description: J.D. is a confident and independent boy who is sociable with people. He tends to be a little dominant with other puppies.
History: J.D. and his siblings were caged up by workers after their mother was tragically knocked down by a truck in Tuas.","admin","2018-07-15"),
("Oppa","A","","M","2010-12-01","Cross Breed","","1","1","1","1","oppa-1740.jpg","Description: Oppa is a very sweet, gentle and easy going boy who loves human attention. He is good with children, puppies and most other dogs (though selective with a few males). He loves walks and walks very well on leash. Being low maintenance, Oppa would be the ideal dog for a first time dog owner.
History: Oppa was a stray living at a cemetery where he had sired many offsprings over the years. He was found with a severe wound on his ear and was caught to be sterilised and released as part of our TNRM programme. However due to his pleasant temperament, we decided to rehome him instead of releasing him back.","admin","2018-07-15"),
("Owi","A","","F","2018-05-01","Cross Breed","","1","1","1","1","owi-1741.jpg","Description: Owi is a shy and gentle girl who is affectionate once she warms up to you.
History: Owi was a stray living with her siblings at a cemetery.","admin","2018-07-15"),
("Omei","A","","F","2018-05-01","Cross Breed","","1","1","1","1","omei-1742.jpg","Description: Omei is timid and sweet girl who needs a little time to warm up.
History: Omei was a stray living with her siblings at a cemetery.","admin","2018-07-15"),
("Odi","A","","M","2001-05-01","Cross Breed","","1","1","1","1","odi-1743.jpg","Description: Odi is a handsome but shy and gentle boy who becomes friendly and active once he is familiar with you.
History: Odi was a stray living with his siblings at a cemetery and was caught to be sterilised and released as part of our TNRM programme. However due to his pleasant temperament, we decided to rehome him instead of releasing him back.","admin","2018-07-15"),
("Spain","A","","M","2013-01-01","Cross Breed","","1","1","1","1","spain-1744.jpg","Description: Spain is a handsome dog with a beautiful and unique coat. He walks very well on leash, is human friendly and good with other dogs.
History: Spain was given up by his previous owner and was kept in a boarding kennel for 5 years.","admin","2018-07-15"),
("Nitnoy","A","","M","2018-11-01","Cross Breed","","1","1","1","0","nitnoy-1745.jpg","Description: With his black, shiny coat and floppy ears, Nitnoy can pass off as a black labrador. The scars on his back are a testimony to his tenacity and will to live when he was found badly injured as a young puppy. Now fully recovered, Nitnoy is a typical puppy… goofy, excitable and lovable. He is a little shy when he is in a new environment but is very affectionate with people he is familiar with. Nitnoy knows to sit to wait for his food and treats, can walk on leash and does his business on the pee pad.
History: Nitnoy was born to a stray mother at Sungei Buloh Wetland Reserve. When he was only 2 - 3 weeks old, he was found with a huge life threatening maggot infested wound.","admin","2018-07-15")

      ');
  
      DB::statement("update adopt set slug = lower(replace(name, ' ', '-'))");
      DB::statement("update adopt set colour = ''");
      DB::statement("update adopt set location = 'ARC'");
    }

    public function down()
    {
      Schema::dropIfExists('adopt');
    }
}
