<?php

use App\Models\Enums\AdoptStat;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AdoptTable extends Migration
{
    public function up()
    {
      Schema::create('adopt', function (Blueprint $table) {
        $table->increments('adopt_id');
        $table->char('stat', 1);
        $table->string('name', 50);
        $table->string('slug', 50);
        $table->char('gender', 1);
        $table->date('birthday');
        $table->string('breed', 50);
        $table->string('colour', 20);
        $table->boolean('microchip');
        $table->boolean('vaccinate');
        $table->boolean('sterilise');
        $table->boolean('hdb');
        $table->string('image', 50);
        $table->string('microchip_no', 40)->nullable();
        $table->date('microchip_date')->nullable();
        $table->date('vaccinate_date1')->nullable();
        $table->date('vaccinate_date2')->nullable();
        $table->date('vaccinate_date3')->nullable();
        $table->date('sterilise_date')->nullable();
        $table->string('vet', 40)->nullable();
        $table->string('location', 30)->nullable();
        $table->string('location_other', 30)->nullable();
        $table->string('health', 500)->nullable();
        $table->string('behaviour', 500)->nullable();
        $table->string('history', 500)->nullable();
        $table->dateTime('rescued_on')->nullable();
        $table->string('posted_by', 30);
        $table->dateTime('posted_on');
        //$table->boolean('has_foster');
        //$table->boolean('can_sponsor');
        $table->string('desc', 2000)->nullable();
        $table->softDeletes();
      });
  
      //export from adoptadog
      //SELECT `name`, 'A' as `stat`, '' as `slug`, `gender`, `birthday`, `breed`, '' as `colour`, 1 as `microchip`, 1 as `vaccinate`, 1 as `sterilise`, if(hdb = 'Y', 1, 0) as `hdb`, `image`, replace(replace(adopt_desc, '"', '\"'), "'", "\'") as `desc`, 'admin' as `posted_by`, '2018-07-15' as `posted_on` FROM `adopt` WHERE post_user = 'asd' and adopt_stat = 'a'
      
      DB::statement("
INSERT INTO `adopt` (`name`, `stat`, `slug`, `gender`, `birthday`, `breed`, `colour`, `microchip`, `vaccinate`, `sterilise`, `hdb`, `image`, `desc`, `posted_by`, `posted_on`) VALUES
('Natasha', 'A', '', 'F', '2013-03-01', 'Cross Breed', '', 1, 1, 1, 0, 'natasha.jpg', '<p>A bright and curious girl, Natasha is loving yet independent. Loves to hop onto your lap for kisses. Natasha and her sisters, Nathalie and Nadia, were rescued from a farm in Neo Tiew.</p>', 'admin', '2018-07-15'),
('Lucas', 'A', '', 'M', '2012-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'lucas.jpg', 'Lucas is a local cross breed who is great with people. He is playful and affectionate. Lucas was one of the many starving strays who used to scrounge for food in the wilds of Lim Chu Kang.', 'admin', '2018-07-15'),
('Trudy', 'A', '', 'F', '2012-07-01', 'Cross Breed', '', 1, 1, 1, 0, 'trudy_65.jpg', '<p>Trudy is playful and friendly. Trudy is one of a litter of 5 puppies found in the Tuas area which were surrendered to the AVA.</p>', 'admin', '2018-07-15'),
('Spotty', 'A', '', 'M', '2011-09-01', 'Cross Breed', '', 1, 1, 1, 0, 'spotty.jpg', 'Spotty is active, affectionate, human-friendly, good with children and selective with dogs, although he does get along pretty well with most dogs. He is also very food/treats motivated, that makes him very trainable and he learns fast. For more info on him: http://www.sportyspotty.com. Spotty was found wandering at a market in Ang Mo Kio looking lost, tired and hungry. We suspected that he had been abandoned ', 'admin', '2018-07-15'),
('Yasmin', 'A', '', 'F', '2012-06-01', 'Cross Breed', '', 1, 1, 1, 0, 'yasmin.jpg', 'Yasmin is a very sweet puppy and is very affectionate towards her caregivers. She is attentive and loves to play with other dogs. She has a wonderful temperament and is well behaved all the time. Yasmin is a very smart puppy and will make a great companion for anyone. Yasmin was rounded up together with a few other dogs and puppies at Yishun Park and sent to the AVA .', 'admin', '2018-07-15'),
('Yana', 'A', '', 'F', '2012-07-01', 'Cross Breed', '', 1, 1, 1, 0, 'yana.jpg', 'Yana is loving and manja. Yana was rounded up together with a few other dogs and puppies at Yishun Park and sent to the AVA ', 'admin', '2018-07-15'),
('Yves', 'A', '', 'M', '2012-07-01', 'Cross Breed', '', 1, 1, 1, 0, 'yves.jpg', 'Yves is the only boy among the pups so he tends to be a bit dominant. Yves was rounded up together with a few other dogs and puppies at Yishun Park and sent to the AVA', 'admin', '2018-07-15'),
('Sheena', 'A', '', 'F', '2010-04-01', 'Cross Breed', '', 1, 1, 1, 1, 'sheena.jpg', 'Playful and friendly, loves to cheww. Rescued from an army camp in Sungei Gedung.', 'admin', '2018-07-15'),
('Jacob', 'A', '', 'M', '2010-01-01', 'Cross Breed', '', 1, 1, 1, 1, 'jacob.jpg', 'Headstrong and dominant, rescued from Jurong Island', 'admin', '2018-07-15'),
('Fannie', 'A', '', 'F', '2010-02-01', 'Cross Breed', '', 1, 1, 1, 1, 'fannie.jpg', 'Friendly. The smallest of her litter.  Rescued from a carpark opposite the Tampines fire station with her 4 siblings.', 'admin', '2018-07-15'),
('Fido', 'A', '', 'M', '2010-02-01', 'Cross Breed', '', 1, 1, 1, 0, 'fido.jpg', 'Friendly. Rescued from a carpark opposite the Tampines fire station with his 4 siblings ', 'admin', '2018-07-15'),
('Avery', 'A', '', 'F', '2008-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'avery.jpg', 'A little wary of strangers but warms up quite fast. Calm, quiet and easy to manage.  ASD was alerted to Avery\'\'s plight towards the end of 2009. She was a young female who had been impregnated by a member of a pack of stray dogs roaming the MacRitchie Reservoir area. Avery was living in the jungle in Adam Drive with her 2 puppies and barely had enough food to survive, let alone feed her pups. The 2 puppies were caught by a man driving a van one day and as Avery was his next target, she was quickly rescued.', 'admin', '2018-07-15'),
('Linus', 'A', '', 'F', '2008-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'linus.jpg', ' A happy and active boy who always welcomes visitors. Linus was born in a coffee shop at Kranji and was adopted by a worker when he was only 3 weeks old. However, he was not looked after or fed properly and began running a very high fever and almost died before we rescued him ', 'admin', '2018-07-15'),
('Mommy Girl', 'A', '', 'F', '2006-01-01', 'Cross Breed', '', 1, 1, 1, 1, 'mommygirl.jpg', 'Quiet and friendly. Mommy Girl was a stray in the Ubi area and gave birth to 8 puppies in an open carpark. All her puppies have already found forever homes except for Zeus who shares the same kennel as her at the ARC. Mother and son are very close.', 'admin', '2018-07-15'),
('Zeus', 'A', '', 'M', '2007-07-01', 'Cross Breed', '', 1, 1, 1, 0, 'zeus.jpg', 'Active and playful. Rescued from Ubi with his 7 siblings and mother ', 'admin', '2018-07-15'),
('Luna', 'A', '', 'F', '2008-06-01', 'Cross Breed', '', 1, 1, 1, 1, 'luna.jpg', 'Very active, intelligent and affectionate. Rescued from Lim Chu Kang ', 'admin', '2018-07-15'),
('Biscuit', 'A', '', 'M', '2007-10-01', 'Cross Breed', '', 1, 1, 1, 0, 'biscuit.jpg', 'Active and playful. She was rescued by a vet.', 'admin', '2018-07-15'),
('Moon', 'A', '', 'F', '2008-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'moon.jpg', 'A very sweet girl who is gentle and quiet and good with humans.  Rescued from a flooded drain in the Lim Chu Kang area together with her 3 puppies, all of whom have since been adopted.', 'admin', '2018-07-15'),
('Yummie', 'A', '', 'M', '2008-02-01', 'Cross Breed', '', 1, 1, 1, 0, 'yummie.jpg', ' Friendly and playful as a puppy but has grown shy and timid due to lack of socialisation with humans. Rescued from Yishun.', 'admin', '2018-07-15'),
('Kranji Girl', 'A', '', 'F', '2007-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'kranjigirl.jpg', 'Needs time to warm up to people. ASD took her in as a stray to be sterilised and then released (TNR) but later decided to keep her and find her a home.', 'admin', '2018-07-15'),
('Noisy', 'A', '', 'M', '2007-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'noisy.jpg', 'Noisy is a big baby who likes to play rough and jump on people. He is very good with humans and will welcome people he recognises with loud and happy barks. He was a stray at Kranji coffee shop who was rescued as pest control was trying to catch him.', 'admin', '2018-07-15'),
('Winner', 'A', '', 'M', '2009-03-01', 'Cross Breed', '', 1, 1, 1, 0, 'winner.jpg', 'So far he has not tried to attack any humans but he can be quite rough and boisterous, jumping on people and biting objects. However with treats, he can do a sit and wait and also walks well on leash.  Winner was found in Woodlands when he was a month old and was adopted one month later. However he was returned to ASD as the adoptive family complained about him biting the domestic help. This could be due to the fact that the family did not give Winner much attention or training. ', 'admin', '2018-07-15'),
('Polly', 'A', '', 'F', '2008-06-01', 'Cross Breed', '', 1, 1, 1, 0, 'polly.jpg', ' Takes time to warm up to people. She was found all alone in Pasir Panjang at one month of age, crying with hunger.', 'admin', '2018-07-15'),
('Furgie', 'A', '', 'F', '2007-10-01', 'Cross Breed', '', 1, 1, 1, 0, 'furgie.jpg', '<p>Rescued from a construction site in Mandai.</p>', 'admin', '2018-07-15'),
('Nature', 'A', '', 'F', '2016-05-01', 'Cross Breed', '', 1, 1, 1, 0, 'nature.jpg', '<p>Was very playful and affectionate as a puppy but has grown quite timid and shy due to lack of interaction with people. Found at Macritchie Reservior.</p>', 'admin', '2018-07-15'),
('Leo', 'A', '', 'M', '2009-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'leo-122.jpg', '<p>Friendly and happy to see people. A hit and run victim found in a drain in the Lim Chu Kang area. Suffered two broken legs but has since recovered.</p>', 'admin', '2018-07-15'),
('Lucky Strike', 'A', '', 'M', '2008-06-01', 'Cross Breed', '', 1, 1, 1, 0, 'luckystrike.jpg', '<p>A little timid. Afraid of heavy vehicles and loud noises. Offspring of Tiger Stripe.</p>', 'admin', '2018-07-15'),
('Black Bingo', 'A', '', 'M', '2007-06-01', 'Cross Breed', '', 1, 1, 1, 0, 'blackbingo.jpg', '<p>Selective with people. Would make a good guard dog as he is alert at all times and barks at strangers. Found in Ang Mo Kio. Was run over by a lorry and had to undergo surgery on his hind leg</p>', 'admin', '2018-07-15'),
('Lava', 'A', '', 'F', '2009-05-01', 'Cross Breed', '', 1, 1, 1, 0, 'lava.jpg', 'A shy puppy, happy to lick and enjoy a pat once she gets to know you, but slow to warm up. Lacks confidence in new environments; will need time to adjust and slow introductions to new people and environments. Easy to handle, non-aggressive, enjoys company of other dogs.
Lava\'\'s personality will emerge once she\'\'s in a safe and loving home. A delightful pup, great pet in the right home. Part of a pack of strays in one of our feeding programmes in Kranji this little sweetheart was targeted for neuter & release in Sept 2009 but she so endeared herself to the kennel staff with her friendly personality and waggy tail that after spaying we decided to place her in our rehoming programme.
Her mother is a medium sized brown/white local cross.', 'admin', '2018-07-15'),
('Elf', 'A', '', 'F', '2008-02-01', 'Cross Breed', '', 1, 1, 1, 0, 'elf.jpg', 'Intelligent and alert but needs time to warm up to people.  Elf was found by the side of the road in the Lim Chu Kang area. She was 6 - 7 months old then but her rescuers initially thought that she was only 4 months old as she was tiny due to malnutrition. Her sister had died of starvation and Elf just stayed close to her body as there was nowhere else for her to go. When the vet checked her teeth for her age, it was found that Elf had been chewing on stones and dried leaves to survive.', 'admin', '2018-07-15'),
('Kodomo', 'A', '', 'F', '2006-05-01', 'Cross Breed', '', 1, 1, 1, 0, 'kodomo.jpg', '<p>Very jumpy and active. Barkish if confined.</p>', 'admin', '2018-07-15'),
('Lucky Hawkins', 'A', '', 'M', '2012-06-01', 'Cross breed', '', 1, 1, 1, 1, 'luckyhawkins.jpg', '<div>Description: Lucky Hawkins is a happy, confident, trusting and manja boy. His right hind leg is slightly weak because of his dislocated hip but he walks (and even trots) fine and is very relaxed and comfortable on leash. He can be a bit rough when playing so he would need a good pack leader who can discourage such bad habits.</div>\r\n<div>&nbsp;</div>\r\n<div>History: Lucky Hawkins was a stray who was cared for by the smallholders at a hawker centre in Tuas. He was hit by a motorcycle one day and suffered a dislocated hip.</div>', 'admin', '2018-07-15'),
('Siew Mai', 'A', '', 'M', '2008-07-01', 'Cross Breed', '', 1, 1, 1, 0, 'siewmai.jpg', '<div>Siew Mai is friendly, laid back and calm and easy to walk on leash.</div>\n<div><br /></div>\n<div>History: Siew Mai was a factory dog who was abandoned because the management moved out.</div>', 'admin', '2018-07-15'),
('Salt', 'A', '', 'F', '2010-01-01', 'Cross Breed', '', 1, 1, 1, 1, 'salt.jpg', '<div>Salt is very calm and sweet and loves affection from people. She is intelligent and has learnt to sit on command. She is quite playful with other dogs, and loves her daily walks.</div>\n<div><br /></div>\n<div>History: Salt was found wandering around a housing estate in the Havelock Road area for about three weeks before she was rescued. She had a chain collar on her so she was probably abandoned.</div>', 'admin', '2018-07-15'),
('Gucci', 'A', '', 'M', '2013-08-01', 'Cross Breed', '', 1, 1, 1, 0, 'gucci_316.jpg', '<p>Description: Gucci is a cute and chubby puppy who is the more alpha and dominant of the 2 brothers.</p>\r\n<p>History: Gucci and his brother Prada are offspring of a Tuas factory stray.&nbsp;</p>', 'admin', '2018-07-15'),
('Lucky Boy', 'A', '', 'M', '2008-07-01', 'Cross Breed', '', 1, 1, 1, 0, 'lucky boy_320.jpg', '<p>Description: Lucky Boy was rescued as he needed to be treated for cancer at the vet but after he was cured, his rescuer decided to rehome him instead of releasing him back as he has a good temperament and is friendly towards people. He has learnt to walk comfortably on leash.</p>\r\n<p>History: Lucky Boy was a stray from Woodlands who contracted a transmissible tumor. However after a course of chemotherapy, he is completely cured.&nbsp;</p>', 'admin', '2018-07-15'),
('Louie', 'A', '', 'M', '2013-11-01', 'Cross Breed', '', 1, 1, 1, 0, 'louie_332.jpg', '<p>Description: Louie is the only one in his pack with big, round, floppy ears which makes him look like a labrador puppy. He is a happy boy who loves his toys and being hugged.</p>\r\n<p>History: Louie is one out of a litter of ten puppies from a stray female in the Pandan Loop area.</p>', 'admin', '2018-07-15'),
('Ke Ke', 'A', '', 'M', '2013-09-01', 'Cross Breed', '', 1, 1, 1, 1, 'ke ke_335.jpg', '<p>Description: Ke Ke may be shy initially but he is very affectionate once he warms up. He is an intelligent boy who will benefit from training.</p>\r\n<p>&nbsp;</p>\r\n<p>History: Ke Ke was rescued from Tuas with his brother, Ai Ai.</p>', 'admin', '2018-07-15'),
('Ai Ai', 'A', '', 'M', '2013-09-01', 'Cross Breed', '', 1, 1, 1, 0, 'ai ai_336.jpg', '<p>Description: Ai Ai is shy but warms up after he gets acquainted. He is intelligent, playful and good natured.</p>\r\n<p>History: Ai Ai was rescued from Tuas with his brother, Ke Ke.&nbsp;</p>', 'admin', '2018-07-15'),
('Kirstie', 'A', '', 'F', '2014-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'kirstie_360.JPG', '<p>Description: Kirstie is an adorable girl who is confident and quick to learn.</p>\r\n<p>&nbsp;</p>\r\n<p>History: Kirstie was rescued from a canal by the Kranji Expressway (KJE) with her 3 siblings after 2 other siblings were caught by the authorities.</p>', 'admin', '2018-07-15'),
('Bruno', 'A', '', 'M', '2010-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'bruno_363.jpg', '<p>Description: Bruno is a very handsome boy and looks like he could be a rottweiler cross. He possesses a happy and friendly nature and an extremely waggy tail! He is excellent indoors and is careful around furniture (no shredding or clawing at furniture) but he needs to know what is considered a toy and what is not. He is eager to be trained, but not overly excitable. Bruno is extremely perceptive and knows how to read your mood. He will only seek attention from you when he knows you are free. Otherwise he will keep his distance and is content to just watch you and wait for you to pay attention to him.</p>\r\n<p>&nbsp;</p>\r\n<p>History: Bruno was found abandoned in Ponggol with heart worm and tick fever. He has already been treated for these conditions and is in the pink of health now.</p>', 'admin', '2018-07-15'),
('Tiffany', 'A', '', 'F', '2013-09-01', 'Cross Breed', '', 1, 1, 1, 0, 'tiffany_365.jpg', '<p>Description: Tiffany has a sweet and gentle disposition. She is a little shy but warms up fairly quickly and once she does, she is very friendly and affectionate. Tiffany enjoys walks and is good on the leash. She is a little clumsy at times and we suspect that the sight in her right eye must have been affected when she suffered a head trauma when she was younger.</p>\r\n<p>History: Tiffany was found lying motionless by a worker in Tuas when she was only 3 months old. She remained listless for about a week and slept most of the time. She perked up eventually and before long, she was standing, then walking then running. We concluded that she had suffered a head trauma which rendered her immobile temporarily. However, we suspect that the trauma might have caused her to lose sight in the right eye.</p>', 'admin', '2018-07-15'),
('Flappy', 'A', '', 'F', '2013-12-01', 'Cross Breed', '', 1, 1, 1, 0, 'flappy_370.jpg', '<p>Description: Flappy is active as a puppy should be. But she is also gentle and loving and walks very well on her leash. She hardly ever barks and seems to have a preference towards ladies. She does chew things when she is at home alone so she should be confined if no one is home. She is independant and not an attention seeker. On the whole, she is lovely and very sweet and easy to manage.&nbsp;</p>\r\n<p>History: Flappy was rescued from an industrial area in Geylang.</p>', 'admin', '2018-07-15'),
('Elly', 'A', '', 'F', '2014-02-01', 'Cross Breed', '', 1, 1, 1, 0, 'elly_416.jpg', '<p>Description: Elly has a sweet disposition but takes a while to warm up to people and other dogs. She\'\'s paper trained, understands basic commands and loves walks.</p>\r\n<p>History: Elly was a stray puppy living with her 2 siblings at a workers\'\' dormitory in Tuas when she was caught and impounded by the authorities.</p>', 'admin', '2018-07-15'),
('Lucy', 'A', '', 'F', '2014-03-01', 'Cross Breed', '', 1, 1, 1, 0, 'lucy_519.jpg', '<p>Description: Looking at Lucy, you will never guess that she came so close to death. She is a playful and active little sweetheart but also very strong willed and bold - a true mark of a survivor. She shows affection by playfully nipping your fingers and whimpers softly when she cannot see anyone but is quiet when she is around you.</p>\r\n<p>History: Lucy was found in a very deep drain in Lim Chu Kang and was in danger of being swept away before she was rescued.</p>', 'admin', '2018-07-15'),
('Lottie', 'A', '', 'F', '2012-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'lottie_535.jpg', '<p>Description: Lottie is a charmer and wags her tail constantly. She smiles at you and gently takes treats from your hands. She loves to be patted and having her ears ruffled.</p>\r\n<p>History: Lottie suddenly appeared in the Lim Chu Kang area and was rescued as she could not fend for herself. When she was brought to the vet to be checked up, she was found to be sterilised so she was obviously abandoned.</p>', 'admin', '2018-07-15'),
('Phelix', 'A', '', 'M', '2014-03-01', 'Cross Breed', '', 1, 1, 1, 0, 'phelix_544.jpg', '<p>Description: Very loving once warmed up, playful.</p>\r\n<p>History: Pete was saved from a factory which was closing down just in the nick of time as he tested positive for canine parvovirus which can be fatal. Fortunately he received the necessary treatment and has now fully recovered.</p>', 'admin', '2018-07-15'),
('Ding Ding', 'A', '', 'M', '2014-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'ding ding_548.jpg', '<p>Description: Ding Ding is an excellent and obedient companion. He enjoys playing with his family members. Although timid at first, Ding Ding slowly but surely gets accustomed to new environments quickly. He is intelligent and sweetly vocalises his needs such as when he is hungry or needs to use the bathroom. Ding Ding is a curious, friendly, brave and handsome little boy who doesn\'\'t ask for much.</p>\r\n<p>History: Ding Ding was a stray puppy living with his 2 siblings at a workers\'\' dormitory in Tuas when he was caught and impounded by the authorities.</p>', 'admin', '2018-07-15'),
('Bobbi', 'A', '', 'F', '2012-01-01', 'Cross Breed', '', 1, 1, 1, 1, 'bobbi_549.jpg', '<p>Description: Bobbi is a very friendly and affectionate dog who likes being in the company of people.</p>\r\n<p>History: Bobbi was a stray living an idyllic life in the Brickland Road area together with a few other dogs. When one of the pack members got caught by the authorities, we decided to whisk Bobbi and her friends to safety.</p>', 'admin', '2018-07-15'),
('Hercules', 'A', '', 'M', '2009-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'hercules_550.jpg', '<p>natured dog. He is always happy to meet people and make new friends.</p>\r\n<p>History: Hercules was kept in a small cage when he was a young puppy resulting in him being bow legged. Fortunately, he was adopted by an expatriate family who lived in a big house with a garden but when the family relocated back to Australia, they left Hercules and another dog, Yvette, behind.</p>', 'admin', '2018-07-15'),
('Jolene', 'A', '', 'F', '2014-10-01', 'Cross Breed', '', 1, 1, 1, 1, 'jolene_551.jpg', '<p>Description: Jolene is a happy go lucky girl who makes friends instantly with everyone she meets and loves company. She is playful, intelligent and curious.</p>\r\n<p>History: Jolene was stray living at a factory in the Lok Yang industrial area.</p>\r\n<p>&nbsp;</p>', 'admin', '2018-07-15'),
('Jace', 'A', '', 'M', '2014-08-01', 'Local Cross', '', 1, 1, 1, 0, 'jace.jpg', '<p>History: Jace and his 4 siblings were rescued together with their 3-legged mother from a construction site in Lim Chu Kang. One of their other siblings had already been crushed to death in an accident so the environment was too dangerous for them to continue living in.</p>', 'admin', '2018-07-15'),
('Bheen', 'A', '', 'M', '2012-01-01', 'Local Cross', '', 1, 1, 1, 0, 'bheen.jpg', 'Description: Bheen is friendly and confident dog who will make a good guard dog for a loving family.<br><br>History: Bheen was found wandering around a block of HDB flats in the West Coast area. He had a microchip but when the owner was found, he did not want Bheen anymore.', 'admin', '2018-07-15'),
('Polo', 'A', '', 'M', '2011-01-01', 'Local Cross', '', 1, 1, 1, 0, 'polo.jpg', 'Description: Polo is a loveable and goofy boy who loves meeting people and making new friends. He loves his food and walks great on leash. <br><br>History: Polo was living at a factory in Pioneer Road with another dog when the management surrendered them both to the authorities. After we claimed the two dogs from the pound, we sent them to the vet for a health check out and discovered that both had contracted distemper, a deadly and contagious disease. They were warded immediately and spent one month in an isolation ward. Polo managed to pull through but unfortunately the other dog did not make it. Today, Polo is free from distemper and in the pink of health though he still has a slight twitch, a lingering symptom of the disease. ', 'admin', '2018-07-15'),
('Lilibet', 'A', '', 'F', '2010-01-01', 'Local Cross', '', 1, 1, 1, 1, 'lilibet.jpg', 'Description: Lilibet is shy and hesitant on first meeting but once she trusts you, she will come to you for affection.<br><br>History: Lilibet was a stray from the Brickland Road area who was caught by the authorities and bailed out.', 'admin', '2018-07-15'),
('Birthday', 'A', '', 'F', '2014-09-01', 'Local Cross', '', 1, 1, 1, 0, 'birthday.jpg', 'Description: Birthday is playful and is good with other dogs. She needs time to warm up to people but will be loving and affectionate once she knows you. She is paper trained and food motivated.<br><br>History: Birthday was rescued as a 2 month puppy together with her sister in the Lim Chu Kang area. She had been attacked by bigger dogs and sustained several maggot wounds which have since healed. ', 'admin', '2018-07-15'),
('Cara', 'A', '', 'F', '2013-12-01', 'Local Cross', '', 1, 1, 1, 1, 'cara.jpg', 'Description: Cara is super affectionate, sweet and passionate and she is not shy to express it. She simply loves to show her passion by licking you and jumping up on you. She is still learning not to jump on people and is improving a lot! She loves the attention given to her and enjoys it. She is also one that will follow the owner around the house, but at the same time, not too sticky. She has very high energy level, and thus will make a good companion for jogging. Cara also has this special interest in tissue papers and balls, or anything that moves. With all these in your hand, she is able to do simple commands like sit, for example.<br><br>History: As Cara was abused before by previous adopter, she tend to be in cautious mode when she is in fear. Thus, she is not suitable to be around young children or elderly without strict supervision. She is now in road of recovery and has shown tremendous improvement. She will be a perfect dog companion in no time.', 'admin', '2018-07-15'),
('Tam', 'A', '', 'M', '2013-02-01', 'Cross Breed', '', 1, 1, 1, 0, 'tam_735.jpg', '<p>Description: Tam is a handsome and loving boy who takes a short time to warm up to people. He is great with other dogs (a follower) and good with people who are firm with him. He is not high energy and is food motivated. He loves going to the dog run but is not keen on long walks. Tam is trained to do his business outside the house.</p>', 'admin', '2018-07-15'),
('Lucette', 'A', '', 'F', '2013-06-01', 'Cross Breed', '', 1, 1, 1, 1, 'lucette.jpg', '<p>Description: Lucette is a sweet, gentle and extremely friendly girl who is a good mother to her puppies.</p>\r\n<p>History: Lucette was a stray on Jurong Island who was a candidate of our stray sterilisation programme. While awaiting surgery, she gave birth to 7 puppies.</p>\r\n<p>&nbsp;</p>', 'admin', '2018-07-15'),
('Kadek', 'A', '', 'M', '2011-01-01', 'Cross Breed', '', 1, 1, 1, 1, 'kadek.jpg', '<p>Description: Kadek is independent with a placid temperament and is good with people and other dogs. He was named Kadek because of his short legs!</p>\r\n<p>History: Kadek was found straying around Pandan Crescent. Because of his small stature, he was often bullied by the other strays. After he was caught and sterilised, his feeder decided to try to rehome him rather than releasing him.</p>', 'admin', '2018-07-15'),
('Soju', 'A', '', 'M', '2015-05-01', 'Cross Breed', '', 1, 1, 1, 0, 'soju.jpg', '<p>Description: Soju is an active and friendly boy who gets along with other dogs and people. He was initially wary of people but not anymore. In fact, he loves attention now and will follow people everywhere.</p>\r\n<p>History: Soju was found at a void deck in Sembawang without any sibling or mother in sight. Suspected to be abandoned and fearing that he would not be able to fend for himself, he was rescued by a kind lady.&nbsp;</p>', 'admin', '2018-07-15'),
('Tuassie', 'A', '', 'F', '2013-08-01', 'Cross Breed', '', 1, 1, 1, 1, 'tuassie.jpg', '<p>Description: Tuassie is a friendly and playful girl.</p>\r\n<p>History: Tuassie was a stray from Tuas who was caught and impounded by the authorities.</p>', 'admin', '2018-07-15'),
('Sterling', 'A', '', 'M', '2013-01-01', 'Cross Breed', '', 1, 1, 1, 1, 'sterling.jpg', '<p>Description: Sterling is super friendly and affectionate towards people. He is playful and active and is better with female dogs.&nbsp;</p>\r\n<p>History: Sterling was a stray from Sungei Kadut who was caught by the authorities and subsequently offered to animal welfare groups for rehoming because of his good temperament.</p>', 'admin', '2018-07-15'),
('Louisa', 'A', '', 'F', '2015-10-01', 'Cross Breed', '', 1, 1, 1, 0, 'louisa.jpg', '<p>Description: Louisa might be a little shy at first but is a friendly and affectionate girl once she knows you.</p>\r\n<p>History: Louisa was rescued as a 2 month puppy together with her 2 siblings in the Lim Chu Kang area.</p>', 'admin', '2018-07-15'),
('Lambert', 'A', '', 'M', '2015-10-01', 'Cross Breed', '', 1, 1, 1, 1, 'lambert.jpg', '<p>Description: Lambert needs a little time to warm up but once he does, he enjoys cuddles and attention.</p>\r\n<p>History: Lambert was rescued as a 2 month puppy together with his 2 siblings in the Lim Chu Kang area.&nbsp;</p>', 'admin', '2018-07-15'),
('Dexter', 'A', '', 'M', '2015-09-01', 'Cross Breed', '', 1, 1, 1, 0, 'dexter.jpg', '<p>Description: Dexter is an affectionate, calm and shy dog. He will thrive on lots of love from his future adopters who can shower him with kisses. He is paper trained and learning basic commands like sit and down were a breeze to him. This smart and handsome boy is currently undergoing training on leash.</p>\r\n<p>History: Dexter was a stray puppy on Jurong Island who was brought to the mainland to be rehomed as he has a good temperament.</p>', 'admin', '2018-07-15'),
('Chi Chi', 'A', '', 'M', '2013-06-01', 'Cross Breed', '', 1, 1, 1, 1, 'chichi.jpg', '<p>Description: Chi Chi is independent, affectionate and very low maintenance. He is good with children, loves swimming and walks well on leash.</p>\r\n<p>History: Chi Chi was rescued from an abusive family.</p>', 'admin', '2018-07-15'),
('Jordan', 'A', '', 'M', '2014-12-01', 'Cross Breed', '', 1, 1, 1, 0, 'jordan.jpg', '<p>Description: Although a little reserved, Jordan is very sweet. Initially shy around strangers, it doesn\'\'t take long for him to warm up but he needs some some space and patience while getting to know someone new, as well as a calm presence when out on walks.&nbsp;</p>\r\n<p>History: Jordan was a stray on Jurong Island who was badly attacked by several other dogs and almost died from blood lost. He has since recovered and is doing well.</p>', 'admin', '2018-07-15'),
('Snapper', 'A', '', 'M', '2008-01-01', 'Cross Breed', '', 1, 1, 1, 1, 'snapper-1147.jpg', 'Description: Snapper is shy with strangers but will warm up. He is independent and loyal and walks quite well on leash.\nHistory: Snapper was rescued from a hoarder.', 'admin', '2018-07-15'),
('Prada', 'A', '', 'M', '2013-08-01', 'Cross Breed', '', 1, 1, 1, 0, 'prada-1151.jpg', 'Description: Prada is an extremely mild mannered dog who can get along with almost everyone, people as well as dogs. He walks well on leash but can be a little skittish in heavy traffic.\nHistory: Prada and his brother Gucci were born to a stray mother living at a factory in Tuas.', 'admin', '2018-07-15'),
('Sweetheart', 'A', '', 'F', '2011-01-01', 'Cross Breed', '', 1, 1, 1, 1, 'sweetheart-1152.jpg', 'Description: Sweetheart is a loving girl who enjoys playing with toys. She takes a little time to warm up to strangers but once on leash, she follows. She is good on walks and is indoor and grass trained.\nHistory: Sweetheart was rescued when she was heavily pregnant. She gave birth to 10 pups at the vet, most of whom have been rehomed.', 'admin', '2018-07-15'),
('Xiaotiantian', 'A', '', 'F', '2011-06-01', 'Cross Breed', '', 1, 1, 1, 1, 'xiaotiantian-1174.jpg', 'Description: Xiaotiantian has a sweet disposition and is relatively low energy. She is a well behaved girl who likes human contact.\nHistory: Xiaotiantian was a stray from a factory in Lim Chu Kang.', 'admin', '2018-07-15'),
('Christmas', 'A', '', 'F', '2014-08-01', 'Cross Breed', '', 1, 1, 1, 1, 'christmas-1256.jpg', 'Description: Christmas is a shy but friendly girl. The fact that she only has 3 usable legs doesn’t faze her and she can run, jump and climb with no difficulty whatsoever!\nHistory: Christmas was found in Seletar with a mangled front left paw just before Christmas in 2015. We suspect that she had her leg caught in a wild boar trap. We decided against amputating her whole leg and Christmas now wears a soft shoe when she goes on walks to protect her paw.', 'admin', '2018-07-15'),
('Fee Fee', 'A', '', 'M', '2013-08-01', 'Cross Breed', '', 1, 1, 1, 1, 'fee-fee-1261.jpg', 'Description: Fee Fee is a sweet natured and responsive boy who loves nothing more than to be shown affection. He is calm and walks well on leash. He is independent and is contented just to chill by himself.\nHistory: Fee Fee was a stray in Tuas who fell victim to the dreaded disease distemper. He was rescued to be treated and has fully recovered.', 'admin', '2018-07-15'),
('Nelson', 'A', '', 'M', '2014-01-01', 'Cross Breed', '', 1, 1, 1, 1, 'nelson-1263.jpg', 'Description: Nelson is a charming boy who thoroughly enjoys pats and attention and has impeccable manners – gently nudging volunteers at the shelter to let them know he would appreciate more attention and affection. Nelson walks well on leash, does not tug and is easily disciplined.\nHistory: Nelson was a stray in Lim Chu Kang who was caught to be sterilised but he was so friendly that we decided to rehome him instead of releasing him back where he would have been in danger of being caught by the authorities.', 'admin', '2018-07-15'),
('Asher', 'A', '', 'M', '2014-03-01', 'Cross Breed', '', 1, 1, 1, 1, 'asher-1273.jpg', 'Description: Asher is sweet and friendly towards people. He loves affection and attention and is best suited to a family who can be at home with him.\nHistory: Asher was rescued from a construction site.', 'admin', '2018-07-15'),
('Hector', 'A', '', 'M', '2012-01-01', 'Cross Breed', '', 1, 1, 1, 1, 'hector-1353.jpg', 'Description: Hector has a minor handicap. Due to the damage caused by distemper to his nervous system, he suffers from twitching and can only use the left side of his body. However, Hector is a strong boy and has been coping well with his handicap. He is able to hop about and does his business like a normal dog. Hector is now on supplements to stabilise his brain functions and he needs to be on hydrotherapy once a week to strengthen the left side of his body. He is a friendly boy and is good with female and smaller size dogs.\nHistory: When Hector was 3 months old, he was found with a torn ear and sent to the vet for treatment. While at the clinic, he was tested positive for distemper and was also malnourished. He was quarantined at the vet clinic for 4 months before being transferred to a boarding kennel. Hector has since fully recovered from distemper and has been waiting for a home since 2013.', 'admin', '2018-07-15'),
('Audemars', 'A', '', 'F', '2016-11-01', 'Cross Breed', '', 1, 1, 1, 0, 'audemars-1419.jpg', 'Description: Shy at first, Audemars can be playful, lively and sociable once warmed up. She likes to play with her water bowl.\nHistory: Audemars was rescued with her 6 siblings from a factory in Tuas.', 'admin', '2018-07-15'),
('Chopard', 'A', '', 'F', '2016-11-01', 'Cross Breed', '', 1, 1, 1, 0, 'chopard.jpg', 'Description: Chopard is good with people, adults and children alike. Although she has a wobbly right hind leg, her health seems fine otherwise.\nHistory: ', 'admin', '2018-07-15'),
('Tissy', 'A', '', 'F', '2013-07-01', 'Cross Breed', '', 1, 1, 1, 1, 'tissy-1440.jpg', 'Description: Tissy is a timid girl who is looking for a family to give her the TLC she needs and help her learn that the world is not such a scary place after all. Despite her shyness, Tissy is always up for a walk and would be contented with being left alone after that.\nHistory: Tissy was 2 months old when she was rescued from Tuas with 3 other siblings. Their mother was nowhere in sight.', 'admin', '2018-07-15'),
('Terry', 'A', '', 'M', '2014-10-01', 'Cross Breed', '', 1, 1, 1, 1, 'terry-1442.jpg', 'Description: Terry is a sweet and shy boy who can be unsure of new faces. Terry is always eager for his walks but can be quite laid back and gentle at other times of the day, happy with idling on his own.\nHistory: Terry was found alone in a factory in Tuas when it closed down.', 'admin', '2018-07-15'),
('Texas', 'A', '', 'M', '2016-12-01', 'Cross Breed', '', 1, 1, 1, 0, 'texas-1443.jpg', 'Description: Texas is food motivated, warms up quickly and good with adults and kids.\nHistory: Texas was rescued from Tuas where he had been bullied by older dogs.', 'admin', '2018-07-15'),
('Semchi', 'A', '', 'F', '2014-06-01', 'Cross Breed', '', 1, 1, 1, 0, 'semchi-1449.jpg', 'Description: Semchi is friendly, playful and very food motivated. He pulls a little on walks so he needs a strong handler.\nHistory: Semchi was a factory stray who was caught and impounded by the AVA.', 'admin', '2018-07-15'),
('Siao Hei', 'A', '', 'M', '2013-08-01', 'Cross Breed', '', 1, 1, 1, 1, 'siao-hei-1492.jpg', 'Description: Siao Hei is a sweet and very petite boy who is well behaved and walks well on leash. Because of his kidney issues, Siao Hei would need to be on a low protein diet and require once or twice weekly subcutaneous fluid therapy.\nHistory: Siao Hei was rescued from a factory when the workers there noticed he was not eating but drinking a lot of water. He was diagnosed as having mild kidney failure.', 'admin', '2018-07-15'),
('Kathi Boy', 'A', '', 'M', '2015-06-01', 'Cross Breed', '', 1, 1, 1, 0, 'kathi-boy-1493.jpg', 'Description: Kathi Boy is good with humans and dogs. He loves walks and receiving pats from people. He is paper and grass trained.\nHistory: Kathi Boy was a hungry stray who came to a factory in Tuas looking for food and was rescued.', 'admin', '2018-07-15'),
('Enzo', 'A', '', 'M', '2017-02-01', 'Cross Breed', '', 1, 1, 1, 0, 'enzo-1495.jpg', 'Description: Enzo was very shy when he was first rescued but has since earnt to crave for hugs and attention from humans.\nHistory: Enzo was a stray puppy who was looked after by a cemetery caretaker.', 'admin', '2018-07-15'),
('Xiao Hei', 'A', '', 'M', '2009-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'xiao-hei-1498.jpg', 'Description: Xiao Hei is a very friendly boy and despite his age, acts like a happy and excitable puppy when he’s around people he is familiar with.\nHistory: Xiao Hei was rescued from the Brickland Road area after his leg was injured by a wild boar trap.', 'admin', '2018-07-15'),
('Tully', 'A', '', 'M', '2017-02-01', 'Cross Breed', '', 1, 1, 1, 0, 'tully-1499.jpg', 'Description: Tully is a playful boy but quite wary when he meets new people.\nHistory: Tully was a stray puppy who was looked after by a cemetery caretaker.', 'admin', '2018-07-15'),
('Freda', 'A', '', 'F', '2017-06-01', 'Cross Breed', '', 1, 1, 1, 0, 'freda-1503.jpg', 'Description: Freda is sweet but very shy girl who takes some time to warm up. She is very playful and loves being with other dogs. She will be suitable for a family who has an older dog in the house to mentor her.\nHistory: Freda and her siblings were born to a stray mother around the Fishery Port Road area.', 'admin', '2018-07-15'),
('Milo', 'A', '', 'M', '2017-06-01', 'Cross Breed', '', 1, 1, 1, 0, 'milo-1504.jpg', 'Description: Milo loves people. He will always approach you with a waggy tail even for just a few seconds of attention. He is a cheerful and trusting puppy who doesn’t mind being hugged and touched even while he is sleeping.\nHistory: Milo was rescued with his sister from Jalan Lekar where his stray mother resided with a pack of dogs.', 'admin', '2018-07-15'),
('Konbu', 'A', '', 'M', '2013-02-01', 'Cross Breed', '', 1, 1, 1, 1, 'konbu-1505.jpg', 'Description: Konbu needs a little time to warm up but once he is familiar with you, he is a loving boy who enjoys walks and attention. He was bitten by his mother when he was a puppy hence his face and jaw is slightly disfigured. Konbu understands basic commands and will be more suitable for a firm and patient adopter who has some experience. He also has thyroid issues and would need to be on lifelong medication.\nHistory: Konbu was one of 4 puppies born to a stray mother in the west. He was adopted as a puppy but was returned because of personal issues within the family.', 'admin', '2018-07-15'),
('Teddy', 'A', '', 'M', '2012-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'teddy-1509.jpg', 'Description: Teddy is a very handsome and majestic looking boy who looks like a bear. Despite his enormous size, Teddy is very much a puppy at heart who yearns for affections and is a great kisser!\nHistory: Teddy was left behind with his mother Poppy after the factory they resided in shifted out in January 2016. They were rescued by some kind souls but both were unfortunately found to be heartworm positive. They have both received treatment and are now heartworm free.', 'admin', '2018-07-15'),
('Kimchi', 'A', '', 'M', '2004-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'kimchi-1510.jpg', 'Description: Kimchi is a beautiful dog in terms of looks and temperament. Despite his age, his health is very good though he has a lump on his behind which has been diagnosed as a benign tumour. This boy will make a great family dog as he is very friendly with people and good with kids. He is generally ok with other dogs but better with females. With males, he may try to challenge but he is not aggressive.\nHistory: Kimchi was given up when his owner relocated to USA.', 'admin', '2018-07-15'),
('Darly', 'A', '', 'F', '2017-06-01', 'Cross Breed', '', 1, 1, 1, 0, 'darly-1525.jpg', 'Description: Darly is very sweet and quiet girl. She can be very endearing despite her shyness. She takes a longer time to open up to new people but when she gets comfortable, she can also be quite mischievous when she\'\'s ready to play.\nHistory: Darly was rescued with her siblings from Jalan Lekar where her stray mother resided with a pack of dogs.', 'admin', '2018-07-15'),
('Macrae', 'A', '', 'M', '2015-12-01', 'Cross Breed', '', 1, 1, 1, 0, 'macrae-1527.jpg', 'Description: Macrae is still regaining his groove after being given up by his family. He will not approach people he meets for the first time, but gets friendlier subsequently. The handsome boy enjoys his walks and is likely to become more sociable with more interaction with volunteers.\nHistory: Macrae is from a litter of 6 puppies who were born to a factory dog in Tuas. He was adopted but given up after a year as his adopters did not have the time to train him.', 'admin', '2018-07-15'),
('Nami', 'A', '', 'F', '2014-01-01', 'Cross Breed', '', 1, 1, 1, 1, 'nami-1528.jpg', 'Description: Nami is a gorgeous girl who takes time to warm up to people. Following her recovery from a wire-trap injury, she has slowly emerged from her shell and become more sociable. She is very chill and enjoys leisurely walks.\nHistory: Nami was a stray in Lim Chu Kang who was badly injured by a wire trap.', 'admin', '2018-07-15'),
('Wilbur', 'A', '', 'M', '2010-07-01', 'Cross Breed', '', 1, 1, 1, 0, 'wilbur-1529.jpg', '<p>Description: Wilbur warms up fairly quickly to people and is quite affectionate. Because he was kept in an cage without being taken out for such a long time, he is gradually acquainting himself with being on leash and outdoors, and building up his stamina. History: Wilbur was kept in a small and low cage at a factory in Woodlands for several years and was never taken out for walks.</p>', 'admin', '2018-07-15'),
('Tao Bao', 'A', '', 'F', '2017-05-01', 'Cross Breed', '', 1, 1, 1, 0, 'tao-bao-1532.jpg', 'Description: Tao Bao was shy with people but great with other dogs. Once warmed up, she is affectionate yet independent.\nHistory: Tao Bao was caught accidentally when she walked into a trap laid for her mother as part of a TNR (trap-neuter-release) programme.', 'admin', '2018-07-15'),
('Karen', 'A', '', 'F', '2012-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'karen-1537.jpg', 'Description: Karen is a sweet and very affectionate girl who loves everyone and is good with other dogs. Call her and she will walk up to you with a smile plastered on her face. Give her a scratch on her head and you’ve got yourself a shadow who will follow you around. She enjoys her baths and her walks!\nHistory: Karen was born at Tuas South, one out of a litter of four. She resided in the parking area of a huge shipyard where she was friendly with the workers. Unfortunately when Karen was around 3 years old, she was caught and impounded by the authorities due to complaints about her excessive barking towards strangers.', 'admin', '2018-07-15'),
('Fin', 'A', '', 'M', '2017-06-01', 'Cross Breed', '', 1, 1, 1, 0, 'fin-1567.jpg', 'Description: Fin is playful and friendly and in the midst of learning how to walk on leash. He is both pee pad and grass trained.\nHistory: Fin and his siblings were rescued from Tuas where they were desperately looking for food.', 'admin', '2018-07-15'),
('Eevee', 'A', '', 'F', '2017-05-01', 'Cross Breed', '', 1, 1, 1, 1, 'eevee-1569.jpg', 'Description: Eevee is a very sweet, affectionate and petite girl. She is generally good with other dogs but will get a little jealous and want her share of attention if you spend too much time with another dog. She walks pretty well on leash but has a tendency to hop around like a kangaroo when in grassy areas!\nHistory: Eevee was rescued from under a lorry when she was a very young puppy.', 'admin', '2018-07-15'),
('Minion', 'A', '', 'F', '2016-01-01', 'Cross Breed', '', 1, 1, 1, 1, 'minion-1570.jpg', 'Description: Minion is a low energy, calm, submissive and shy dog who takes a little time to warm up to people. She is an easily contented dog who is satisfied to have a roof over her head, warm meals and slow walks. She loves to be clean so will do her business outside.\nHistory: Minion was a stray young mother who was recused after she was involved in an accident at a construction site. She was in much in pain when she limped to her feeders for help. Her pelvis was cracked and her left hind leg was fractured. The accident also caused her to lose her sight in her right eye. But with her strong will, her condition continued to improve day by day and now she has recovered under her fosterer\'\'s care though she only uses 3 legs to walk and run.', 'admin', '2018-07-15'),
('Tricks', 'A', '', 'M', '2013-04-01', 'Cross Breed', '', 1, 1, 1, 0, 'tricks-1571.jpg', 'Description: Tricks has a beautiful coat and an intense gaze. He enjoys the company of people and will lie down for rubs and to play. Tricks tends to be mouthy but he doesn’t mean any harm. He has a towel at the shelter that he enjoys chewing and tugging. Because of his background, some time and patience to get to know his quirks would be useful. He will show displeasure by growling.\nHistory: Tricks was from a container yard in Penjuru and was chained up as he liked to chase people and cars. He was bitten by a pack of dogs that came into the yard one day and the wound worsened to the point that he had to have his hind leg amputated.', 'admin', '2018-07-15'),
('Yoko', 'A', '', 'F', '2012-07-01', 'Cross Breed', '', 1, 1, 1, 1, 'yoko-1572.jpg', 'Description: Give Yoko enough time and attention, and she will likely warm up to you. She is a bit wary of strangers and will not approach them, but is friendly and more playful around people she knows. The lovely lady also enjoys having her own space for some me-time.\nHistory: Yoko was among several dogs and puppies at Yishun Park that were rounded up by the AVA.', 'admin', '2018-07-15'),
('Joe', 'A', '', 'M', '2010-05-01', 'Cross Breed', '', 1, 1, 1, 0, 'joe-1574.jpg', 'Description: Joe is missing a hind leg but this has not stopped him from enjoying walks and being outdoors. Joe has some food aggression and may not be friendly to everyone, but he has mellowed over the years. To those he strikes a connection with, he is extremely sweet, enthusiastic and loyal. This special boy has gorgeous, soulful eyes.\nHistory: Joe was rescued in March 2012, a victim of an llegal wild boar trap in the vicinity of Old Jurong Road. By the time he was discovered, severe infection had already set in and his leg had to be amputated. However he was also found to be heartworm positive so his surgery had to be delayed until he recovered.', 'admin', '2018-07-15'),
('Cha Cha', 'A', '', 'F', '2014-01-01', 'Cross Breed', '', 1, 1, 1, 1, 'cha-cha-1575.jpg', 'Description: Cha Cha is a sweet girl who is happy to have others as the centre of attention. She is shy but will warm up with time and make a lovely companion. She has also become slightly more playful after being paired with a more active and sociable dog at the kennels.\nHistory: Cha Cha was a member of a friendly pack of strays residing at Sungei Buloh Nature Reserve. Unfortunately visitors issued a complaint so they were forced to be removed.', 'admin', '2018-07-15'),
('Lola', 'A', '', 'F', '2012-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'lola-1576.jpg', 'Description: Lola is initially shy but lights up when she sees people she is familiar with. A gentle approach is best when getting to know this lovable and charming lady. Lola is unfussy and fairly independent.\nHistory: Lola was an unsterilised stray female in the Lim Chu Kang area who was attracting a lot of unwanted attention from the stray male dogs. The owner of one of the farms there threaten to catch and dispose of her as the male dogs were ruining the vegetation while chasing her.', 'admin', '2018-07-15'),
('Tau Sar', 'A', '', 'M', '2014-10-01', 'Cross Breed', '', 1, 1, 1, 0, 'tau-sar-1577.jpg', 'Description: Tau Sar and his kennel mate Leen Yong are the big, macho boys of the shelter. They look slightly intimidating and play and wrestle with each other the way boys do, but are actually very friendly and sociable. Tau Sar will beckon you to enter the kennel with inquisitive eyes and stay still for pats. He enjoys walks and, with his short and distinctive dark brown coat, will be a handsome and low-maintenance addition to the family.\nHistory: Tau Sar was a stray who was caught by the authorities and subsequently offered to animal welfare groups for rehoming because of his good temperament.', 'admin', '2018-07-15'),
('Leen Yong', 'A', '', 'M', '2013-10-01', 'Cross Breed', '', 1, 1, 1, 0, 'leen-yong-1578.jpg', 'Description: Leen Yong and his kennel mate Tau Sar are the big, macho boys of the shelter. They look slightly intimidating and play and wrestle with each other the way boys do, but are actually friendly and warm up quickly to humans. Leen Yong is the slightly more playful one. He hurries out of his “room” in the kennel when people enter and loves treats and walks/runs.\nHistory: Leen Yong was a stray who was caught by the authorities and subsequently offered to animal welfare groups for rehoming because of his good temperament.', 'admin', '2018-07-15'),
('Jackie Chan', 'A', '', 'M', '2017-02-01', 'Cross Breed', '', 1, 1, 1, 0, 'jackie-chan-1579.jpg', 'Description: Meet Jackie Chan, named for his amazing accuracy at catching flies with his mouth! Jackie is a very sweet boy who loves his human companions. He is selective with other dogs and will do better as a single dog. Jackie is a loyal and intelligent dog who will do well under a firm but loving owner.\nHistory: Jackie Chan was found abandoned in the Upper Thomson area.', 'admin', '2018-07-15'),
('Clovis', 'A', '', 'M', '2016-02-01', 'Cross Breed', '', 1, 1, 1, 0, 'clovis-1583.jpg', 'Description: Clovis is the friendliest of of the 3 scared and skittish brothers. He is the one that most readily approaches people to sniff them and to take treats. Clovis is now full-grown and has shared some of his youthful vitality with his older kennel-mate Nature. He is still quite skittish and would benefit from a patient and calm presence, including when out on walks.\nHistory: Clovis and his 2 brothers were rescued from Jurong Island when they were puppies.', 'admin', '2018-07-15'),
('Kyla', 'A', '', 'F', '2017-09-01', 'Cross Breed', '', 1, 1, 1, 1, 'kyla-1584.jpg', 'Description: Given how she was found with such a painful injury (one can only guess what led to her broken leg and how long she had been suffering prior to her rescue), it’s no surprise that Kyla is rather shy with strangers, especially young children. She is also anxious of noisy traffic so she tends to struggle when she crosses a road or when there are moving cars or motorcycles nearby. But all she needs is a little patience. Allow her some time to warm up and you will be bowled over by her very sweet temperament. Kyla is also very good with other dogs and walks well on leash.\nHistory: Kyla was found limping in Kranji and a visit to the vet revealed that her right hind leg was fractured but already healing by itself so surgery was not required. She currently walks with a perfect gait although she has a barely noticeable limp when she goes up or down steps.', 'admin', '2018-07-15'),
('Calbee', 'A', '', 'F', '2017-07-01', 'Cross Breed', '', 1, 1, 1, 1, 'calbee-1587.jpg', 'Description: Calbee is very food motivated. Although she is good with other dogs, she is very shy with people and will need time and patience. She is peepad trained, has no aggression and walks well on leash.\nHistory: Calbee was a stray from a factory in Tuas who was caught for TNR but because of her sweet disposition, we decided to try to rehome her.', 'admin', '2018-07-15'),
('Bingsu', 'A', '', 'F', '2016-12-01', 'Cross Breed', '', 1, 1, 1, 1, 'bingsu-1588.jpg', 'Description: Bingsu is well behaved and is very friendly towards people and other dogs. She is paper trained and walks well on leash.\nHistory: Bingsu was rescued from the Bukit Panjang area when she was around 5 months old. She had suffered trauma to her hind legs but has since recovered.', 'admin', '2018-07-15'),
('Luke', 'A', '', 'M', '2013-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'luke-1589.jpg', 'Description: Luke is very friendly toward people and walks well on leash. He is quite a chill, easy going and independent boy.\nHistory: Luke was a stray from the Lim Chu Kang area who was often bullied by the other dogs in his pack. His spate of bad luck continued when he was caught by the authorities but fortunately for him, his feeder noticed that he was missing and contacted us to claim him from the pound.', 'admin', '2018-07-15'),
('Marley', 'A', '', 'M', '2017-03-01', 'Cross Breed', '', 1, 1, 1, 1, 'marley-1591.jpg', 'Description: Marley is happy to play alone with his toys as he’s totally independent. Once he warms up and trusts you he’ll stick his head on your lap for some love or ask you to play fetch with his ball. He can be as active or as lazy as you want. Making him a great pacemaker as your jogging buddy or your personal guard dog, keeping you company as you work on your computer in the evenings. He is super food motivated and super smart, which makes him very trainable. But needs someone with experience and patience to handle him as he\'\'s not friendly towards other dogs. He is both paper and grass-trained. He has no separation anxiety. However, he needs to be walked in the morning and evenings.\nHistory: Marley was originally from a factory in Mandai but because it was going to be razed, a kind hearted driver decided to relocate him to a worksite in Jalan Lekar. Unfortunately Markey met with an accident at the new location and broke his leg. He had to undergo a costly and long drawn surgery but thankfully has recovered very well and can now walk, run and jump with no issues.', 'admin', '2018-07-15'),
('Apple', 'A', '', 'F', '2010-12-01', 'Cross Breed', '', 1, 1, 1, 1, 'apple-1594.jpg', 'Description: Apple is personable and likes attention.\nHistory: Unknown', 'admin', '2018-07-15'),
('Black Black', 'A', '', 'M', '2013-06-01', 'Cross Breed', '', 1, 1, 1, 1, 'black-black-1595.jpg', 'Description: Black Black is good with people and selected dogs.\nHistory: Black Black was abandoned by his rescuer at a boarding kennel.', 'admin', '2018-07-15'),
('Blackie', 'A', '', 'M', '2012-05-01', 'Cross Breed', '', 1, 1, 1, 0, 'blackie-1596.jpg', 'Description: Blackie is a super friendly and confident boy who loves head pats. He is generally a calm dog who likes slow walks but is nervous when there is lightning and thunder. Although missing his front right paw, Blackie does not act like a handicapped dog.\nHistory: Blackie was staying at a factory in Tuas South but when the company relocated, he was left behind. His rescuer has no idea how he lost his front right paw. She thinks it could either be caused by an accident or an illegal wild boar trap.', 'admin', '2018-07-15'),
('Da Fu', 'A', '', 'F', '2013-11-01', 'Cross Breed', '', 1, 1, 1, 1, 'da-fu-1597.jpg', 'Description: Da Fu is an extremely small local cross breed, the size of a corgi. She is sweet and gentle but a little shy.\nHistory: Da Fu was abandoned by her rescuer at a boarding kennel.', 'admin', '2018-07-15'),
('Harry', 'A', '', 'M', '2012-11-01', 'Cross Breed', '', 1, 1, 1, 0, 'harry-1598.jpg', 'Description: Harry is very friendly and is always excited and happy to meet people.\nHistory: Harry was abandoned by his rescuer at a boarding kennel.', 'admin', '2018-07-15'),
('Nugget', 'A', '', 'M', '2014-06-01', 'Cross Breed', '', 1, 1, 1, 0, 'nugget-1599.jpg', 'Description: Nugget is an effervescent, excitable and friendly boy who can sometimes get over excited. He enjoys his walks but would need to be guided on leash.\nHistory: Nugget was rescued as puppy.', 'admin', '2018-07-15'),
('Ron', 'A', '', 'M', '2014-04-01', 'Cross Breed', '', 1, 1, 1, 0, 'ron-1600.jpg', 'Description: Ron is gentle and a little shy but friendly towards people. He enjoys walks but needs coaxing sometimes when on the leash.\nHistory: Ron was abandoned by his rescuer at a boarding kennel.', 'admin', '2018-07-15'),
('Mei Mei', 'A', '', 'F', '2011-03-01', 'Cross Breed', '', 1, 1, 1, 1, 'mei-mei-1601.jpg', 'Description: Mei Mei is a calm girl who loves company and enjoys walks.She sustained an injury to her right front leg before she was rescued and now walks with a limp.\nHistory: Unknown', 'admin', '2018-07-15'),
('Brody', 'A', '', 'M', '2014-03-01', 'Cross Breed', '', 1, 1, 1, 1, 'brody-1610.jpg', 'Description: Brody is a gentle soul who takes a bit of time to warm up to new faces or new dogs but he doesn\'\'t bark or growl. His favourite activities include going out for walks and watching traffic. Brody would happily sit on the pavement watching cars go by for hours, if he was allowed. He also grins from ear to ear when being patted and massaged. Brody is fully grass-trained.\nHistory: Brody is a stray from Brickland Road. The rest of his pack have all been rescued and rehomed, leaving him alone.', 'admin', '2018-07-15'),
('Warren', 'A', '', 'M', '2018-01-01', 'Cross Breed', '', 1, 1, 1, 0, 'warren-1611.jpg', 'Description: Warren is a little timid so he will take awhile to approach new faces. He loves to be with people that he is comfortable with and he already knows basic commands like “sit”, “shake hands” and “high five”.\nHistory: Warren is 1 of 7 siblings found in the Seletar area.', 'admin', '2018-07-15'),
('Lara', 'A', '', 'F', '2017-02-01', 'Cross Breed', '', 1, 1, 1, 1, 'lara-1612.jpg', 'Description: Lara is a bundle of joy in a compact body. She gives affection wholeheartedly and enjoys the company of humans and dogs alike. With her contagious smile, she never fails to brighten anyone\'\'s day. She walks well on leash. If you\'\'re looking for a fun girl who will love you unconditionally, Lara may be the dog for you.\nHistory: Lara was stray from a Choa Chu Kang Cemetery who was caught to be sterilised but due to her friendly nature, the decision was made to rehome her.', 'admin', '2018-07-15'),
('Meiji', 'A', '', 'F', '2014-05-01', 'Cross Breed', '', 1, 1, 1, 1, 'meiji-1613.jpg', 'Description: With her black rimmed eyes and white fur, Meiji is a standout amongst her canine friends. Once she warms up, Meiji\'\'s a friendly, affectionate girl who loves head rubs. Show her any affection and you will be rewarded with her contagious smile and wagging tail. A gentle and loving girl, Meiji would be a welcome addition to any family.\nHistory: Meiji was a stray from Tuas.', 'admin', '2018-07-15'),
('Ariel', 'A', '', 'F', '2015-03-01', 'Cross Breed', '', 1, 1, 1, 1, 'ariel-1614.jpg', 'Description: Pretty Ariel has transformed from a stray who shies away from humans to a sweet tempered girl who yearns for affection. She is still shy with strangers and will need time to warm up. She is very good with other dogs. However, as she can be protective of her food, she should be fed away from other dogs in the household, if any. If yours is a family with adults or teenagers, with the patience to allow her time to settle in, Ariel will be a loyal addition to your family.\nHistory: Ariel was rescued by her feeder as she was attacked by many male dogs in the Tuas South area.', 'admin', '2018-07-15'),
('Bambi', 'A', '', 'F', '2011-02-01', 'Cross Breed', '', 1, 1, 1, 0, 'bambi-1615.jpg', 'Description: Bambi is a shy girl who takes a little while to warm up. She is a big baby who loves soft toys and towels but is scared of storms and cars. She enjoys walks (she currently goes on a short walk in the morning and a long walk at night) and rolling on grass.\nHistory: Bambi was adopted when she was around a year old by a family who kept her outdoors on their landed property. In Sept 2016, someone found her wandering at a park and posted a “found” notice on Facebook. Bambi’s rescuer recognised her and went to collect her. When approached, her adopter claimed that Bambi had escaped and did not want her back.', 'admin', '2018-07-15'),
('Bunny', 'A', '', 'F', '2016-03-01', 'Cross Breed', '', 1, 1, 1, 1, 'bunny-1616.jpg', 'Description: Bunny is 100% sunshine and an absolute darling. She is extremely sociable and trusting. The happy, gorgeous girl enjoys being around people and is also generally friendly to other dogs. She is still getting used to walking on a leash and needs some guidance when out on walks, as she can get distracted and try to walk in random directions. She tends to crouch down or sit when a vehicle is going past. She would be a great fit for a household that can spend a good amount of quality time with her daily.\nHistory: Bunny was a stray who was caught by the authorities and subsequently offered to animal welfare groups for rehoming because of her good temperament.', 'admin', '2018-07-15'),
('Sakae', 'A', '', 'M', '2016-03-01', 'Cross Breed', '', 1, 1, 1, 1, 'sakae-1617.jpg', 'Description: When Sakae was first rescued, he was extremely timid and would shy away from human contact. Now, whilst still shy with strangers, Sakae has transformed into an affectionate, curious boy who will display his playful side once he warms up. His comical and quizzical expressions add to his charm. If yours is a family with adults or teenagers, with the patience to allow him time to settle in, Sakae will be a fun addition to your family.\nHistory: Sakae was rescued from a factory in Senoko in an appalling state when he was only 7 months old. He was severely malnourished and tick-infested.', 'admin', '2018-07-15'),
('Nubia', 'A', '', 'F', '2018-02-01', 'Cross Breed', '', 1, 1, 1, 0, 'nubia-1618.jpg', 'Description: Although Nubia is a shy puppy, she warms up to people after a short while.\nHistory: Nubia was rescued together with her siblings from the Neo Tiew area.', 'admin', '2018-07-15'),
('Jade', 'A', '', 'F', '2011-08-01', 'Cross Breed', '', 1, 1, 1, 1, 'jade-1619.jpg', 'Description: Jade is a quiet and calm girl who enjoys walks. She is very good on the leash and warms up easily to new faces.\nHistory: Jade was born in a factory but was rescued as a puppy and housed in a kennel since then.', 'admin', '2018-07-15'),
('Pebble', 'A', '', 'F', '2011-08-01', 'Cross Breed', '', 1, 1, 1, 0, 'pebble-1620.jpg', 'Description: Pebble is an independent gal but loves the company of people. She still needs some training on her leash walking.\nHistory: Pebble was born in a factory but was rescued as a puppy and housed in a kennel since then.', 'admin', '2018-07-15'),
('Flint', 'A', '', 'M', '2011-08-01', 'Cross Breed', '', 1, 1, 1, 0, 'flint-1621.jpg', 'Description: Flint is an independent and low maintenance dog who loves human companionship. He walks well on leash and enjoys his walks.\nHistory: Flint was born in a factory but was rescued as a puppy and housed in a kennel since then.', 'admin', '2018-07-15'),
('Kimmy', 'A', '', 'F', '2018-03-01', 'Cross Breed', '', 1, 1, 1, 0, 'kimmy-1622.jpg', 'Description: Kimmy is a sweet but shy little girl but once she has warmed up, she is happy and loving.\nHistory: Kimmy is one of a litter of 4 puppies from a factory in Tuas South.', 'admin', '2018-07-15'),
('Kirin', 'A', '', 'F', '2018-04-01', 'Cross Breed', '', 1, 1, 1, 0, 'kirin-1623.jpg', 'Description: Kirin is a confident and fearless puppy. She is very friendly and will run up to greet people she doesn’t even know. She is food motivated and a fast learner. Kirin can play fetch and has learnt to sit and wait for her food. She is fine to be left alone in a playpen for a few hours without making any noise, content to just sleep or play with her toys. Kirin can already walk on leash, is grass trained and partially pee pad trained.\nHistory: Kirin was rescued as a lone puppy from Kranji.', 'admin', '2018-07-15'),
('Windsor', 'A', '', 'M', '2013-05-01', 'Cross Breed', '', 1, 1, 1, 1, 'windsor-1624.jpg', 'Description: Windsor has a very distinctive bark so you\'\'ll never mistake his vocals for another dog’s! He is excitable, likes people and loves his walks even more.Windsor is still in the process of getting more socialised and responsive to people, but he displays quite an even temperament and is not very reactive to other dogs. He is also good on leash. However he can get a bit mouthy when interacting with people.\nHistory: Windsor was impounded by the authorities and subsequently offered to animal welfare groups for rehoming because of her good temperament. We suspected that Windsor might have had an owner before as he was already microchipped and sterilised.', 'admin', '2018-07-15'),
('Briggs', 'A', '', 'M', '2015-05-01', 'Cross Breed', '', 1, 1, 1, 1, 'briggs-1625.jpg', 'Description: Briggs is initially a bit shy around people but soon warms up to them. That said, he is also in the process of getting more socialised -- revealing more of his personality and being more responsive towards people. He gets scared and may snap if people try to carry him or lift him when holding him back (such as when preventing him from dashing out of his kennel). The greedy boy loves his food so this may be just the way to bond with him.\nHistory: Briggs was previously caged up at a factory in Bedok and was surrendered to the authorities after complaints from the public.', 'admin', '2018-07-15'),
('Bertie', 'A', '', 'M', '2015-05-01', 'Cross Breed', '', 1, 1, 1, 1, 'bertie-1626.jpg', 'Description: Bertie is a bit reserved and takes some time to get to know. He is still in the process of being more comfortable around people and is quite mild mannered around them, but can be pretty feisty towards other dogs. He is fairly high energy and tugs quite a lot on walks, thus more suited for an experienced dog owner.\nHistory: Bertie was previously caged up at a factory in Bedok and was surrendered to the authorities after complaints from the public.', 'admin', '2018-07-15'),
('Maia', 'A', '', 'F', '2015-06-01', 'Cross Breed', '', 1, 1, 1, 1, 'maia-1627.jpg', 'Description: With her wiry brown fur and petite size, Maia is quite a rare find! Her white beard and front are unique traits that distinguish her from the rest. Having only been in the shelter for a few months, Maia is still a little wary of people but grows confident when she’s out on walks. She gets along well with her furry friends and is sure to appear before you if she smells food on you (yes she’s a cute greedy little one!)\nHistory: Maia was a stray from Tuas.', 'admin', '2018-07-15'),
('Missy', 'A', '', 'F', '2016-06-01', 'Cross Breed', '', 1, 1, 1, 1, 'missy-1628.jpg', 'Description: Missy’s brown-tipped tail stands out from her pretty white coat. While the rest of her furry friends are running around, you can expect to find her resting in her bed or sunbathing in the open. But don’t be fooled by her quiet front - Missy enjoys her walks just as much as the rest! It’s when her tail comes up and she starts warming up to you. She walks extremely well on leash, stopping once every few steps to make sure she’s in sync with your pace.\nHistory: Missy was a stray from Tuas.', 'admin', '2018-07-15'),
('Starley', 'A', '', 'F', '2017-10-01', 'Cross Breed', '', 1, 1, 1, 1, 'starley-1629.jpg', 'Description: Starley is super friendly and approachable, even when she meets you for the first time. She is also an affectionate girl who enjoys being patted and is always ready for hugs and cuddles. Even though she lost half of her tongue during a dog fight, that does not stop her from spreading her cheerfulness to the people around her. She walks well on leash, and is always curious to explore her surroundings.\nHistory: Starley was a stray from Tuas.', 'admin', '2018-07-15'),
('Yukee', 'A', '', 'F', '2016-12-01', 'Cross Breed', '', 1, 1, 1, 1, 'yukee-1630.jpg', 'Description: Yukee is a sweet and gentle girl despite coming to us very shy. She can be a little hesitant when meeting people for the first time, but with a little time and patience, she blossoms into an incredibly wonderful and loving girl. Both affectionate and Low maintenance, she is a quiet girl who would be contented with sitting and relaxing on her own but would enjoy a head scratch or two as well. A shy dog, but food motivated, Yukee is just a few treats away from being your new best friend!\nHistory: Yukee was a stray from Tuas.', 'admin', '2018-07-15'),
('Horatio', 'A', '', 'M', '2017-10-01', 'Cross Breed', '', 1, 1, 1, 0, 'horatio-1631.jpg', 'Description: Horatio is a very sweet, gentle and lovable boy but needs time to warm up to his surroundings. He likes to be hugged at times but dislikes baths or having his nails clipped though he is fine to be cleaned with wet tissues. If he dislikes you touching certain areas, he will use his paws to push your hands away. A habit of his is to bite/nip fingers as a form of playing. Horatio has always been in the company of other dogs so he might have some separation anxiety when left alone. On walks, Horatio will pull a little in the beginning but will settle into a rhythm though he can be wary and excitable in new surroundings so he will need some assurance. Horatio enjoys his food so do not leave any food unattended as he will steal it! Horatio is pee pad trained.\nHistory: Horatio was rescued as a very young puppy along with his siblings.', 'admin', '2018-07-15'),
('Robin', 'A', '', 'M', '2017-01-01', 'Cross Breed', '', 1, 1, 1, 1, 'robin-1632.jpg', 'Description: Robin is good with people and tends to form a tight bond with his caregiver. However he can be mischievous in the company of other dogs. He walks well on leash and enjoys roaming.\nHistory: Robin as a stray from the Lim Chu Kang area who was caught by the authorities but fortunately for him, his feeder noticed that he was missing and contacted us to claim him from the pound. Robin was found to be heartworm positive but has since undergone treatment.', 'admin', '2018-07-15'),
('Jumbo', 'A', '', 'M', '2017-05-01', 'Cross Breed', '', 1, 1, 1, 0, 'jumbo-1633.jpg', 'Description: Jumbo is a cheerful and moderately active dog. He is friendly with people but not very good with some male dogs.\nHistory: Jumbo was a stray from Tuas.', 'admin', '2018-07-15'),
('King', 'A', '', 'M', '2013-05-01', 'Cross Breed', '', 1, 1, 1, 0, 'king-1634.jpg', 'Description: King is a family dog though he has been trained as a guard dog. He is an intelligent boy who is good with people but not good with other dogs. He loves pats and sidling up to people. King is best suited for adopters with experience.\nHistory: King was commercially boarded when his owner went away. Unfortunately the owner is away indefinitely and the kennel had to close so King has no home now.', 'admin', '2018-07-15'),
('Maka', 'A', '', 'M', '2012-05-01', 'Cross Breed', '', 1, 1, 1, 0, 'maka-1635.jpg', 'Description: Maka is of a unique breed, offspring of a Pedigree wildboar hunting line from Louisiana. Maka loves long runs, hikes and playing with his handler. He is quick and agile, a fast learner that thrives in play and dog obedience. He has not lived with other dogs and needs to be under close supervision with children. He will thrive under a firm handler and loving family.\nHistory: Maka came to Singapore from Hawaii 4 years ago. He has had a single owner from the time he was a puppy. His owner is unable to provide the care Maka needs due to work commitments and frequent travelling.', 'admin', '2018-07-15');
      ");
  
      DB::statement("update adopt set slug = lower(replace(name, ' ', '-'))");
      DB::statement("update adopt set colour = ''");
      DB::statement("update adopt set location = 'ARC'");
    }

    public function down()
    {
      Schema::dropIfExists('adopt');
    }
}
