<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class PageTable extends Migration
{
    public function up()
    {
      Schema::create('page', function (Blueprint $table) {
        $table->increments('page_id');
        $table->string('title', 50);
        $table->string('slug', 50);
        $table->string('meta_desc', 10)->nullable();
        $table->text('content');
      });
      
      
      DB::statement(
        "INSERT INTO `page` (`page_id`, `title`, `slug`, `content`) VALUES
(1, 'Who We Are', 'who-we-are', '<p><strong>Who We Are&nbsp;</strong><br><br>Action for Singapore Dogs (ASD) was established in December 2000 as a non-profit organization with the mission to improve the welfare of stray and abandoned dogs in Singapore. ASD was officially registered with the Registry Of Societies on the 3rd July 2002.&nbsp;<br><br>We aim to fulfill our mission through various activities and programs including rescuing, fostering and re-homing of stray and abandoned dogs, advocating sterilization as a means of controlling the stray population, heightening public awareness of the responsibilities involved in pet ownership and highlighting the virtues of our local dogs.&nbsp;<br><br>ASD also works with official institutions and other non-governmental organizations in order to synergize the efforts towards alleviating the plight of the local stray dog population. Regular events are organized to raise funds for veterinary care of rescued dogs and to promote adoption of our local dogs.&nbsp;<br><br>As a non-profit, non-governmental organization, all our work is carried out mainly by volunteers and through contributions. Initially comprising of 3 volunteers, the group has now grown to about 20 odd core volunteers.&nbsp;<br><br><strong>Why We Do This&nbsp;</strong></p><p>We believe that all animals big or small deserve a life of love and care, not just a life of fear and survival. There are thousands of healthy stray dogs that are put to sleep every year, due to lack of space, resources and non acceptance by the majority of society.&nbsp;<br><br>We choose to believe that each and every one of them deserve a second chance at life, and that includes the many sick and diseased strays that will never be given that chance to be healed, or a chance to experience the love and warmth of a home.&nbsp;<br><br>We work with a simple philosophy of ‘One dog at a time’, and every dog under our care is precious to us. With that philosophy, we adhere to a very strict code of no-kill, and we will do what it takes to ensure the dogs in our care receive the optimum care and protection, regardless of their health condition.&nbsp;<br><br><strong>The Future&nbsp;</strong></p><p>We aim to generate greater support for this cause and to develop a sturdy foundation of committed members who will be willing to speak up and help these helpless creatures, and to slowly change the bias of society to accept these wonderful creatures, so full of love and loyalty.&nbsp;</p>'),
(2, 'Adoption & Rescue Centre (ARC)', 'adoption-rescue-centre-arc', '<p>The ARC was&nbsp;established in June 2007 and is situated in rustic Lim Chu Kang far from the madding crowd. Since Dec 2000, ASD has been actively rescuing, re-homing and sterilizing the countless stray and abandoned dogs that have been heartlessly discarded by society when they no longer serve their needs</p><p>ASD had been relying on&nbsp;a network of foster&nbsp;families to&nbsp;love and care for&nbsp;the dogs&nbsp;which have been rescued and&nbsp;awaiting adoption, but over&nbsp;the years, the number of dogs&nbsp;needing help far exceed the number of foster homes.</p><p>The ARC will&nbsp;complement&nbsp;our current&nbsp;network of foster homes&nbsp;and&nbsp;has a comfortable capacity of 54 dogs.&nbsp;As the name implies, the ARC will be run on the philosphy of helping dogs that are sick or injured, and healthy,&nbsp;happy puppies and dogs with good temperament who stand a good chance of adoption.</p><p>The centre&nbsp;is not&nbsp;run as&nbsp;a shelter nor a boarding facility as it is hoped that there will be a quick turnaround time for the residents there to be adopted out and for new dogs to come in, ultimately resulting in increased adoption rates.</p><p>In 2008, a new block will be added next to the existing block and this will be used as a boarding home, of which the revenue generated will be channeled to the ARC to maintain the operations.</p><p>Visits to the ARC is by appointment only unless an Open House Day is declared. Do join our mailing list to be kept updated of happenings at the ARC and volunteers are welcome to help maintain the centre and interact with the dogs. Please send us an email at <a href=\"http://asdsingapore.com/wp/contact-us/\"><strong>info@asdsingapore.com</strong></a> if you are keen to help out</p><p>Running the ARC requires a huge amount of resources, and&nbsp;contributions are always needed and appreciated, be it monetary, food, medicine, equipment etc. Please contact us at <a href=\"http://asdsingapore.com/wp/contact-us/\"><strong>info@asdsingapore.com</strong></a> if you wish to contribute or have any ideas that can help generate revenue to maintain the centre.</p>'),
(3, 'Boarding Services', 'boarding-services', '<p>Do you worry about going away and leaving your dog in a kennel environment ? Haven’t had a holiday in years because you couldn’t trust anyone with your dog ?&nbsp;</p><p><br>Now you can rest easy when you leave your dog with us. Like you, we want the best for our dogs. That is why we spare no expense to ensure our dogs get the best treatment possible and the hallmark ASD quality care will be extended to your dog when he/she comes to stay with us.</p>'),
(4, 'Media', 'media', 'Media'),
(5, 'Dog Listener Academy', 'dog-listener-academy', '<p>The love and joy that you can experience from your dog is uniquely special and cannot be described, only experienced. In order to have that fufilling relationship, your dog has to be nurtured and taught to live in harmony and happiness with his human pack, just like a child.</p><p>At the ASD Dog Listener Academy, we believe the best way to have an enriching life with your dog is through communication and cooperation, not conditioning nor coercion. Through our many years of rescue work, we have gained much experience handling and rehabilitating dogs of all types of personality from the highly dominant to the fearful withdrawn. Our goal is to ensure that your dog willingly and happily integrates into your family environment, and understands and cooperates with the social rules.</p><p>We do it without gimmicks and gadgets, and we expound a kind way to dog training. We don’t believe in choking or electrocuting your dog into submission or harsh punishment, but through strong leadership, positive reinforcement and kind correction, your dog will willingly cooperate with you.</p><p>While dogs have a basic set of behavioural traits, no two dogs are alike, and your dog, like yourself, will have his own unique personality traits and habits. As such, we treat each and every dog as a cherished individual.</p><p>Under the Dog Listener Academy, volunteers at the Adoption &amp; Rescue Centre&nbsp; are trained with this philosophy in mind and we conduct educational talks and presentations expounding the benefits of proper training to better understand your dog and to have&nbsp; that fulfilling relationship</p><p>For the&nbsp;Basic Obedience Foundation classes and consultations,&nbsp; we collaborate with a third party dog training school, The Dog Listener Consultancy (www.doglistenerconsultancy.com) who has the same vision and goals.</p><p>At the Basic Obedience Foundation classes and consultations, what diffentiates from the rest is that, on top of learning the basic obedience techniques, you will also learn and apply the all important foundation principles of Amichien (TM) Bonding that will anchor your relationship with your dog.<br><br>Special emphasis will also be placed on individually assessing your dog’s character as well as your relationship with him, and focus will be placed on the areas that will help strenghten your bond with your dog. Time will also be allocated at the end of the class to handle any individual questions or issues.</p><p>For all group courses signed up through the ASD website, The Dog Listener Consultancy will donate 50% of the course fees back to ASD.</p>'),
(6, 'Why Adopt A Dog', 'why-adopt-a-dog', '<p><strong>Cost</strong>&nbsp;<br>It is much cheaper to adopt a dog than to buy one. Versus paying anything from $500 to $2000 from the pet shops or breeders, adopting a dog from ASD only entails a token adoption fee and provides many more benefits. Please refer to the ASD Adoption Package here.&nbsp;<br><br><strong>Telling the truth&nbsp;</strong><br>We are non profit and our priority is the welfare and future of the dogs under our care, it is never about making the sale or about money. As such we are upfront about the character traits and health status of the dog, both good and bad. It is no point masking or hiding certain facts about the dog to accelerate the adoption process only for the new owners to find out about it later, and if they are not prepared for those traits, the dog’s life or future may be in jepordy.&nbsp;<br><br><strong>A Lifetime Of Support&nbsp;</strong><br>Unlike pet shops and breeders, we ‘don’t wash our hands clean once the deal is done’. ASD believes in keeping in contact with their adoptors even past the adoption stage and helping with any problems that may come at various stages.&nbsp;<br><br>However it should be emphasized that this does not provide an avenue for people to ‘try out’ the dog first. Adopting a dog is a lifetime commitment and should be treated seriously. Ultimately, the adoptor needs to have the mindset to work out whatever problems they may face, should there be any. Please refer to the ASD Adoption Package below.&nbsp;<br><br><strong>Low Maintenance&nbsp;</strong><br>Most of our dogs for adoption are cross breed dogs. They are hardy and low maintenace dogs who have been acclimatized to our high humidity and hot environment. They seldom have skin problems or any other genetic defects which are common with pedigree breeds.&nbsp;<br><br><strong>Greater Loyalty</strong>&nbsp;<br>All our dogs are rescued dogs who were either strays or have been abandoned. As a result of their hardship and suffering, most of them are deeply loyal and affectionate because they appreciate the second chance that they are given.</p>'),
(7, 'Adoption Procedure', 'adoption-procedure', '<p>1. From our website www.asdsingapore.com, browse the ‘Dogs For Adoption‘ section where pics of the dogs are posted together with their bio, and note down a few of the dogs you may be interested in.&nbsp;<br><br>2. Contact us by email or call the hotline to enquire on the availability of these dogs. An Adoption Counsellor will discuss with you about your requirements or expectations and in turn give you more information on the dog’s behaviour traits and to highlight areas or aspects which may be pertinent to that dog.&nbsp;<br><br>3. If there is some basic matching between the expectations and the dog’s traits, we will send you an Adoption Application Form to fill up so that we can better understand your background, experience and lifestyle.&nbsp;<br><br>4. A convienient time and date is then set for a non obligatory bonding session where you, the potential adoptor and at least another member of the household will be invited to visit the dog at our Centre or at the foster home. More bonding sessions can also be arranged if you require more time to assess the temperament of the dog.&nbsp;<br><br>5. You, the potential adoptor then take some time (typically 1-3 days) to discuss with your family members and decide.&nbsp;<br><br>6. Should you, the potential adoptor decide to adopt, you will come down to the Centre or the foster home to sign an Adoption Agreement and bring the dog back.&nbsp;<br><br>7. The conditions of the Adoption Agreement are:</p><ul><li>To allow home visits, roughly 2 weeks to 1 month after the adoption, the purpose of which is to see if any assistance can be rendered.</li><li>The dog also need to be licensed, vaccinated, microchipped and sterilized and ASD provides a mandatory, comprehensive, subsidized package here</li></ul>'),
(8, 'Project Adore', 'project-adore', '<p>In the past, if you were living in a HDB flat and wanted to own a local cross breed dog (Singapore Special), it would not have been possible. Since about 80% of the Singapore population lived in HDB flats, we knew this was an obstacle we had to overcome. So ASD, together with SPCA, embarked on a rehoming project called Project ADORE (ADOption and REhoming of dogs), which is a scheme permitting HDB residents to own local cross breed dogs.&nbsp;<br><br>Project ADORE kicked off in April 2012 as a pilot project and due to its success, was formalised in Parliament on 28 May 2014. As at 31 Dec 2015, ASD had successfully rehomed 192 dogs under this scheme.&nbsp;<br><br>To be approved under Project ADORE, a dog must be at least 7 months old, not more than 50 cm in height (from the shoulder to the ground) and under 15 kg in weight.&nbsp;<br><br>This campaign is aimed at supporting our rescues from the time they are about 2 months old until they are 7 months old. This means we have to support each of these puppies for at least five months.&nbsp;<br><br>Sure, sometimes dogs under this scheme are rescued when they are older and are rehomed within weeks or a couple of months. But sometimes, some of them stay with us for years.&nbsp;<br><br>A conservative estimate of maintaining a rescued dog at a shelter is $200 per month. This includes the basic necessities of food, boarding, and tick, flea and heartworm prevention.&nbsp;<br><br>We hope to rehome many more dogs under Project ADORE in 2016. Raising additional funds for this today would mean we could support more rescues and not have to worry about drawing funds away from the estimated 150 dogs we currently maintain.</p>'),
(9, 'Gone to Loving Homes', 'gone-to-loving-homes', 'Gone to Loving Homes'),
(10, 'Sponsor', 'sponsor', 'Sponsor'),
(11, 'Gift Shop', 'gift-shop', 'Gift Shop'),
(12, 'Dogs in Need', 'dogs-in-need', 'Dogs in Need');"
      );
    }

    public function down()
    {
      Schema::dropIfExists('page');
    }
}
